src/components/projects/env/env_detail/env_detail_comp.vue

Signed-off-by: zhangliyu <zhangliyu@koderover.com>
donnot show update_env_var button while env updating

Don't show update_env_var button while env updating

---

src/components/projects/service_mgr/common/service_tree.vue

label width been changed while icon show
use 'visibility' instead of 'display none'

Use style to control service's operation icon

---

src/utilities/onboarding_route.js

cloud_host and k8s has the same 'deploy_type',so use 'basic_facility' to  distinguish

Fix onboading bug

---

src/components/projects/delivery/version/detail.vue

API gets 500 when run artifact deploy.
Don't collect distributeInfo to imagesConfigs.

Fix artifact deploy error.

---

src/components/projects/detail_ope/create.vue

Set deployType to k8s when create cloud host.
How it Works:

Set deployType to k8s when create cloud host.

---

src/components/projects/web_code/code.vue

- when add a helm service, show default values.yaml or first file after import a helm chart.
How it Works:

show default values.yaml

---

src/components/setting/integration/code.vue

Signed-off-by: fansi <fansi4o4@163.com>
the expression of github id is wrong
What's Changed: alter github id to github username

alter github id to github username

---

src/components/projects/env/env_detail/env_detail_comp.vue

- Just show service name of helm instead of projectName-envName-serviceName
How it Works:

Just show service name of helm instead of projectName-envName-serviceName

---

src/components/projects/pipeline/common/run_workflow.vue

Set service is picked when service has build.

Set service is picked when service has build.

---

src/components/setting/integration/account.vue

Set groupFilter is required in LDAP and AD.

---

src/api/index.js
src/components/profile/manage.vue

- Change downloadConfigAPI's route.
- Don't show kubeconfig download temporary.

Change downloadConfigAPI's route.

---

src/components/common/workflow_build_rows.vue
src/components/common/workflow_test_rows.vue

- Add tooltip to repo name.
- Show fullname when reponame is too long.
- workflow_test_rows.vue
- workflow_build_rows.vue
How it Works:

Add tooltip to repo name.

---

src/common/vue_sse/index.js

Change SSE log heartbeat timeout to 3600s
The default timeout period without output is 45 seconds, which is too short to break.

fix(log):Change SSE log heartbeat timeout to 3600s

---

config/prod.env.js
src/App.vue

How it Works:
Show info when app is mounted when environment's type is production.

feat(console):show build info in console when environment's type is production.

---

src/components/projects/common/import_values/repository.vue
src/components/projects/service_mgr/helm/components/common/git_repo.vue

Fix select subgroup error when add helm services, use path replace of name.

fix(repo): fixed select subgroup error

---

src/components/projects/detail_ope/create.vue

Creating helm version can hook external api, after selecting external link in helm project editing page.

feat(helm): can select external link when edit helm project

---

src/components/projects/env/inner_env/create_env_detail.vue

- cant create env when don't add image registry

fix: cant create env when don't add image registry

---

src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

- set build name null if default name already exists

fix(1.8.0): set build name null if default name already exists

---

src/components/setting/registry/manage.vue

set is_default is true when registry not exists

fix:set is_default is true when registry not exists.

---

build/webpack.dev.conf.js
config/index.js

Add 'disableHostCheck' to webpack conf.
Reference [#devserver-disablehostcheck](https://webpack-v3.jsx.app/configuration/dev-server/#devserver-disablehostcheck)

chore(webpack): add 'disableHostCheck' to webpack conf.

---

src/common/task_list.vue

fix: show service name in artifact workflow detail list page

fix: show service name in artifact workflow detail list page

---

src/components/setting/cluster/manage.vue

Don't pass cache property when creating a new cluster.
New:

fix:don't pass cache property when creating a new cluster.

---

src/components/common/test_trigger.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

Fix the trigger method is not displayed when the code source is gerrit.
- Product workflow trigger.
- Test workflow trigger.

fix(trigger):fix the trigger method is not displayed when the code source is gerrit.

---

src/components/projects/pipeline/workflow_multi_task_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/test/common/function/container/task_detail_test.vue
src/components/projects/test/common/function/functionTaskDetail.vue
src/utilities/wordTranslate.js

Signed-off-by: zhangyifei <zhangyifei@koderover.com>
The back-end adds a `Prepare` state for the build and testing process, and the front-end adapts accordingly. 
Support `Prepare` state for the build and testing process.

support `Prepare` state for build/testing

---

config/index.js
src/api/index.js
src/common/repo_select.vue
src/components/setting/config/proxy.vue
src/components/setting/integration/code.vue

Now users no longer has a switch for system repo proxy. They get a button to enable proxy for that specific repo.
-
1. Deleted enable proxy in the repository page
2. Added enable proxy for each of the repository entry. The old repositories will be marked as disabled
How it Works:

Disable global proxy switch and replace it with a switch for each entry

---

src/components/projects/env/createHelmEnv.vue
src/components/projects/env/env_detail/components/updateHelmEnvDialog.vue
src/components/projects/service_mgr/helm/components/common/update_helm_env.vue

Signed-off-by: Min Min <minmin@koderover.com>
enables creating env for existing namespace
Currently creating environment on existing namespace is disabled, this PR removes this limit
How it Works:

enables creating env for existing namespace

---

src/components/projects/detail_ope/home.vue

fix style when project-name is too long.

fix(style):fix style when project-name is too long.

---

src/components/projects/detail_ope/home.vue

fix style when project-name is too long.

 fix(style):fix style when project-name is too long.

---

src/components/projects/delivery/version/k8s/detail.vue
src/components/projects/pipeline/workflow_common_task_detail/task_detail_build.vue

service name support display service components.

feat:service name support display service components.

---

src/components/templateLibrary/dockerfile/fileTree.vue
src/components/templateLibrary/k8s/fileTree.vue

fix(ux):remove tooltip in template name.

fix(ux):remove tooltip in template name.

---

src/components/projects/common/hosting/serviceModules.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue

fix: show image name in host and helm services page

fix: show image name in host and helm services page

---

src/components/projects/build/otherSteps.vue

supports uploading files to object storage in build configuration.

feat:supports uploading files to object storage.

---

src/components/projects/env/env_detail/components/shareEnvDialog.vue

checking status after enable share env.

fix:checking status after enable share env.

---

src/common/chromeTabs.vue

feat:add envType to tab's tooltip.

---

src/common/chromeTabs.vue
src/components/projects/env/env_detail/envDetailComp.vue

fix:using tailCut in env name.

---

src/components/projects/serviceMgr/helm/components/helm/aside.vue

feat:add confirm dialog when saving release name.
Cherry pick for https://github.com/koderover/zadig-portal/pull/731

feat:add confirm dialog when saving release name.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

fix: add build for shared services cannot be clicked

fix: add build for shared services cannot be clicked

---

src/components/projects/env/env_detail/envDetailComp.vue

fix: hide helm environment's updatable status

fix: hide helm environment's updatable status

---

src/components/setting/users/components/roleOperate.vue
src/components/setting/users/editUserInfo.vue
src/components/setting/users/manage.vue
src/components/setting/users/role.vue

- remove console.log and clean code.
- don't show scrollbar in `roles-overview-container`
- change `overflow-x` to `hidden` in users-overview-container
- change size of `el-input` to small
How it Works:

fix:fix style of user container.

---

src/components/projects/build/envVariable.vue
src/components/templateLibrary/builds/envVariable.vue

[fix(typo):fix typo of vars](https://github.com/koderover/zadig-portal/commit/170f6c335abbbfd947d4998d72413f9ae370df65)

fix(typo):fix typo of vars 

---

src/components/projects/build/commonBuild.vue

fix:showcheckbox when jenkins is disabled.

fix:show checkbox when jenkins is disabled.

---

src/components/setting/integration/code.vue

we don't support CodeHub integration for now.
How it Works: delete CodeHub info

fix typo: delete codehub

---

src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/serviceMgr/common/serviceTree.vue

- feat: restart the instance requires confirmation
- fix: the newly created service not be displayed

fix: 1.12.0 bug 

---

src/components/projects/build/envVariable.vue
src/components/templateLibrary/builds/envVariable.vue

missing some spellings & descriptions for `REPONAME_index`/`REPO_index`
What's Changed: update spelling & description

fix typo: update variable spelling & description

---

src/components/projects/env/helmEnv/createHelmEnv.vue

fix: request namespaces when changing clusters

fix: request namespaces when changing clusters

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue

cherry-pick:#1006
- `release_imageSubTask` is undefined when the release method is `object`.
-  fix release method removal not working in workflow's release page.

cherry-pick:#1006

---

src/components/projects/workflow/workflowEditor/customWorkflow/config.js

Problem Summary: missing $ before variable BUILD_URL in common workflow
What's Changed: add the missing $

fix typo: missing $ before variable BUILD_URL

---

src/components/projects/build/envVariable.vue
src/components/projects/workflow/workflowEditor/commonWorkflow/modules/build.vue
src/components/templateLibrary/builds/envVariable.vue

variable `$DIST_DIR` is no longer in use.
remove variable `$DIST_DIR`
document ref: https://github.com/koderover/zadig-doc/pull/368

fix typo: remove useless variable

---

src/components/projects/build/commonBuild.vue
src/components/projects/build/envVariable.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/templateLibrary/builds/envVariable.vue
src/components/templateLibrary/builds/fileEditor.vue

feat:adjusting the behavior of build variables
- once a custom variable has been saved, no modification of the custom name is allowed
- when creating custom variables, don't set the default to sensitive information

feat:adjusting the behavior of build variables

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/plugin.vue

keep typo consistent, ref: https://github.com/koderover/zadig-portal/pull/1098
What's Changed: `是否加密` -> `敏感信息`

fix typo: [cherri-pick 1098]keep typo consistent

---

src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

[fix:show close btn in webhook config.](https://github.com/koderover/zadig-portal/commit/188a5d1737c5afbebfb43eef2638cad09b54d165)

fix:show close btn in webhook config.

---

src/components/projects/build/advancedConfig.vue
src/components/templateLibrary/builds/advancedConfig.vue

add validation to cache folder path.

feat:add validation to cache folder path.

---

src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/editor/codeMirror.vue

add breadcrumb navigator to helm values editor.

feat:add breadcrumb navigator to helm editor.

---

src/assets/css/common/common.less
src/assets/css/theme/index.css

fix(style):remove margin in el-alert__description
before:
after:

fix(style):remove margin in el-alert__description

---

src/components/setting/integration/code.vue

document pull request: https://github.com/koderover/zadig-doc/pull/396
update codehost integration ref link( to make it more precise)

fix typo: update codehost integration ref link

---

src/components/setting/integration/code.vue

fix link: `/` at the end of link will lead to 404
What's Changed: remove `/`

fix typo: fix link

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue

fix:set project prop to current project by default.

fix:set project prop to current project by default.

---

src/components/templateLibrary/builds/fileTree.vue
src/components/templateLibrary/chart/index.vue
src/components/templateLibrary/dockerfile/fileTree.vue

fix:change behavior of the template creation button when there is no permi

fix:change behavior of the template creation button when there is no permission.

---

src/components/projects/build/zadigBuild.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/templateLibrary/builds/zadigBuild.vue

feat:disable build cache by default.
How it Works:

feat:disable build cache by default.

---

src/assets/css/component/service-mgr.less
src/components/projects/serviceMgr/serviceK8s.vue

fix:remove the min-width limit of the k8s yml pane to make dragging more flexible.

fix:remove the min-width limit of the k8s yml pane to make dragging more flexible.
