src/components/projects/guide/helm/info_basic.vue
src/components/projects/guide/not_k8s/not_k8s_info.vue

- modify koderover to zadig;
How it Works:

modify name

---

src/App.vue
src/components/entry/loading.vue
src/router/index.js

add loading page when services not ready
How it Works:

add loading page when services not ready

---

src/api/index.js
src/common/repo_select.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/pipeline/workflow_multi_task_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_test.vue
src/components/projects/service_mgr/common/add_code.vue
src/components/projects/test/common/function/function_detail.vue
src/components/setting/apps/manage.vue
src/components/setting/integration/code.vue

Supports huawei codehub in build
repo-select
workflow-build-detail
workflow-test-detail
How it Works:

Supports huawei codehub in build.

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

Add params 'name' to webhook

---

src/components/projects/common/integration_registry.vue
src/components/setting/registry/manage.vue

Show default reg provider's icon when not exists.

Show default reg provider's icon when not exists.

---

src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/not_k8s/not_k8s_delivery.vue
src/components/projects/web_code/components/helm/help.vue
src/components/setting/apps/manage.vue
src/components/setting/cluster/manage.vue
src/components/setting/config/cache.vue
src/components/setting/config/proxy.vue
src/components/setting/config/quota.vue
src/components/setting/host/manage.vue
src/components/setting/integration/account.vue
src/components/setting/integration/code.vue
src/components/setting/integration/github_app.vue
src/components/setting/integration/jenkins.vue
src/components/setting/integration/jira.vue
src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue

- add help link to https://docs.koderover.com
How it Works:

help docs link

---

src/api/index.js

when run workflow, don't show warning message if error
How it Works:

fix warning

---

src/components/projects/pipeline/common/run_workflow.vue

- when running workflow tasks, add sorting rules to the service list

Support service list sorting

---

config/index.js
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/service_mgr/service_k8s.vue

https://trello.com/c/Ij5idpqn/1491-p1-%E6%9C%8D%E5%8A%A1%E7%8E%B0%E6%9C%89%E9%85%8D%E7%BD%AE%E5%92%8C%E9%85%8D%E7%BD%AE%E5%BA%93%E4%B8%8D%E4%B8%80%E8%87%B4%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%8D%87%E7%BA%A7%E6%8F%90%E7%A4%BA
How it Works:

add dialog

---

src/components/projects/pipeline/common/run_workflow.vue

fixed some services have not build,  there are not show images list when run a ops pipeline;
How it Works:

delete filter has_build

---

src/components/enterprise_mgr/users/manage.vue

There is only one system user, it should not be deleted
How it Works:

limit delete

---

src/components/setting/host/manage.vue
src/components/setting/storage/manage.vue

Show Provider logo in list

---

src/api/index.js
src/components/common/gitfile_tree.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue
src/components/projects/service_mgr/common/service_tree.vue

Supports import yaml from codehub

Supports import yaml from codehub

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

Hide folder when trigger repo source is codehub.

Hide folder when repo source is codehub

---

src/components/setting/integration/code.vue

there are more support for code, update official description
How it Works:

There are more support for code, update official description

---

src/components/projects/build/config_detail.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/web_code/components/common/build.vue

Issue Number: close [#83](https://github.com/koderover/zadig/issues/83)
Build script variables supports workflow's id.

Add  to variables description.

---

src/components/projects/common/not_k8s/add_host.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/setting/host/manage.vue

- there aren't host, show host drawer when add a cloud host service
- optimize host manage
How it Works:

optimize cloud host

---

src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/pipeline/workflow_list.vue
src/mobile/pipelines/pipelines.vue
src/store/modules/workflow_list.js

- optimize request pipeline list
How it Works:

Optimize request pipeline list

---

src/components/projects/common/not_k8s/not_k8s_form.vue

edit pm_deploy_SCRIPTS

---

src/components/projects/service_mgr/common/service_tree.vue

use promise finally to edit loading=false

Fix loading bug

---

arm64.Dockerfile

Signed-off-by: Min Min <minmin@koderover.com>
Arm64 dockerfile added

arm64 dockerfile added

---

src/components/projects/pipeline/workflow_multi_task_detail.vue

add pm deploy column
How it Works:

add deploy pm

---

src/components/projects/common/not_k8s/service_list.vue

add dialog while delete service

add dialog while delete service

---

src/assets/css/component/service-editor.less
src/components/projects/guide/k8s/container/service_editor.vue
src/components/projects/guide/service.vue
src/components/projects/service_mgr/k8s/service_editor.vue
src/components/projects/service_mgr/service_k8s.vue

- fix yaml area auto focus when add a new service
- add placeholder
How it Works:

first focus and placeholder

---

src/components/projects/common/not_k8s/not_k8s_form.vue

add default imageid

---

config/prod.env.js
src/components/entry/login.vue

Show version in login page.
How it Works:

Show version in login page.

---

src/components/projects/common/integration_registry.vue
src/components/setting/registry/manage.vue

- check use if we add first image registry
How it Works:

Use the default option when there is no registry

---

src/common/repo_select.vue

- clear data when request repos
- add loading text
How it Works:

Clear data when request repos

---

src/components/projects/test/common/function/function_detail.vue
src/components/quality_manage/tests/first.vue

- optimize test style
How it Works:

Optimize test configuration style

---

src/components/projects/common/not_k8s/add_host.vue

- host name rules tally with bash's
How it Works:

Validate host name

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

- add trigger name rules
How it Works:

Add trigger name validation rules

---

Dockerfile
amd64.Dockerfile

rename Dockerfile -> amd64.Dockerfile for naming convention

---

src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/k8s/service_aside.vue

- Fix show bug when switch to shared service
How it Works:

Fix show bug when switch to shared service

---

src/components/setting/integration/account.vue

Optimize LDAP integration.
Add description to placeholder
How it Works:

Optimize LDAP integration.

---

src/assets/css/common/build-row.less
src/components/common/workflow_test_rows.vue

Optimize build dialog's style

---

src/components/setting/integration/code.vue

Fix integration-code-container margin

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue
src/components/setting/sidebar.vue

Remove feature check.
Features:
- show_pr_env
- cluster_manager
How it Works:

Remove feature check.

---

src/components/setting/cluster/manage.vue

Remove namespace in cluster management.

Remove namespace in cluster management.

---

src/api/index.js
src/components/projects/env/env_detail/env_detail_comp.vue

Add lazyload to external services. 
Add page params to helm services api.

Add lazyload to external services.

---

src/components/common/gitfile_tree.vue
src/components/projects/common/not_k8s/add_host.vue
src/components/projects/service_mgr/common/service_tree.vue
src/components/projects/service_mgr/k8s/service_aside.vue
src/components/projects/service_mgr/k8s/service_editor.vue
src/components/projects/service_mgr/service_k8s.vue

- if yaml don't save, prompt whether to save;
- add ctrl+s for saving;
- fix some error;
How it Works:

If yaml don't save, prompt whether to save

---

src/common/repo_select.vue
src/components/projects/build/config_detail.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/test/common/function/function_detail.vue
src/components/projects/web_code/components/common/build.vue

optimize style:
- repo select;
- add loading;
- add jump;
- update desc;
How it Works:

optimize style

---

src/api/index.js
src/components/projects/web_code/code.vue
src/components/projects/web_code/components/common/gitfile_tree.vue
src/components/projects/web_code/components/common/repo.vue
src/components/projects/web_code/components/editor/folder.vue

Optimize git file loading api.

Optimize file loading api.

---

src/components/projects/service_mgr/common/build.vue
src/components/projects/web_code/components/common/build.vue

Add project name when create build conf.

Add project name when create build conf.

---

src/components/common/test_trigger.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/artifact_deploy.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/helm/info_basic.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/k8s/info_basic.vue
src/components/projects/guide/not_k8s/not_k8s_delivery.vue
src/components/projects/guide/not_k8s/not_k8s_info.vue

1. fix wrong reference for *-workflow-ops to make the link right
2. use the same pron for user to align the programming style

[bugfix] fix wrong reference for ops workflow + programming style enhancement

---

src/components/projects/env/env_detail/env_detail_comp.vue

Don't show namespace in pm environment.

Don't show namespace in pm environment.

---

src/components/projects/detail_ope/create.vue

- when create a project, user can select admin by the project
How it Works:

when create a project, user can select admin by the project

---

src/components/projects/common/integration_registry.vue
src/components/setting/registry/manage.vue

Add dockerhub to registry provider.

Add dockerhub to registry provider.

---

src/components/projects/env/inner_env/create_env_detail.vue

create pm enviroment don`t show cluster

Don't show cluster when create pm environment.

---

src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue

alter create time to modify time

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

hidden base env by pm project
How it Works:

hidden base env by pm project

---

src/common/repo_select.vue

fix undefined bug

---

src/components/projects/detail_ope/create.vue

Reverts koderover/zadig-portal#66

Revert "when create a project, user can select admin by the project"

---

src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/service_detail/container_log.vue

Add CLI tooltip.

---

package.json
src/main.js
yarn.lock

Add loaders.css 

---

config/index.js
src/api/index.js
src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/serviceModules.vue
src/components/projects/detail_ope/create.vue
src/components/projects/env/createEnv.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/hostEnv/creatHostEnv.vue
src/components/projects/env/inner_env/service_detail.vue
src/components/projects/guide/host/components/host_env_config.vue
src/components/projects/guide/host/components/run_workflow.vue
src/components/projects/guide/host/components/service_build.vue
src/components/projects/guide/host/components/step.vue
src/components/projects/guide/host/host_config.vue
src/components/projects/service_mgr/service.vue
src/components/projects/service_mgr/service_host.vue
src/router/index.js
src/utilities/onboarding_route.js

add external

---

src/components/entry/login.vue

Issue Number: close #71 
Fix variables undefined.

Fix variables undefined.

---

src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/pipeline/common/run_workflow.vue

This reverts commit 5c781f3d10f8f70d7c7dc628fa61c34676c4b9d7.
How it Works:

Revert "Optimize branch loading strategy."

---

src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/common/not_k8s/service_list.vue
src/components/projects/service_mgr/common/service_tree.vue
src/components/projects/service_mgr/service_k8s.vue
src/components/projects/web_code/code.vue

Don't show updateBtn when env list is empty

Don't show updateBtn when env list is empty

---

src/components/users_mgr/users/manage.vue

- hidden delete button for ad users
How it Works:

hidden delete button for ad users

---

src/api/index.js
src/components/entry/home/sub_sidebar.vue
src/components/projects/chart_temp/index.vue
src/components/projects/common/import_values/key_value.vue
src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/helm/aside.vue
src/components/projects/service_mgr/helm/components/helm/help.vue
src/components/projects/service_mgr/helm/components/helm/match_rule.vue

custom match rules

---

src/components/setting/integration/jira.vue

Validate jira host's url.
Don‘t include slash at the end of the jira address.
How it Works:

Validate jira host's url.

---

src/components/entry/home/sidebar.vue
src/components/projects/chart_temp/index.vue
src/components/projects/detail_ope/home.vue
src/router/index.js

- move template repo to project home page
How it Works:

Move template repo to project home page.

---

src/api/index.js
src/components/projects/common/hosting/build.vue
src/components/projects/detail_ope/home.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/basic_info.vue
src/components/projects/env/env_detail/components/recycleDialog.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/env/inner_env/home.vue
src/components/projects/env/outer_env/home.vue
src/components/projects/guide/helm/info_basic.vue
src/components/projects/service_mgr/common/service_tree.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/service_mgr/helm/components/common/update_helm_env.vue
src/components/projects/service_mgr/not_k8s/updateEnv.vue
src/components/projects/service_mgr/service_host.vue
src/components/projects/service_mgr/service_k8s.vue
src/mobile/envs/env_detail.vue
src/mobile/envs/envs.vue
src/store/modules/product_list.js

- Environment SSE api deprecated.

Environment SSE api deprecated.

---

src/components/common/deploy_icons.vue

edit service description

---

src/components/common/deploy_icons.vue
src/components/projects/env/env_detail/env_detail_comp.vue

FIx delete environment btn does not display.

---

src/components/projects/env/env_detail/components/updateHelmEnvDialog.vue
src/components/projects/env/inner_env/create_env_detail.vue

- fix show error when create a helm env or a pm env
- fix error when update the helm env after delete a chart service
How it Works:

Fix helm bugs.

---

src/api/index.js

- change api path `match-rules` to `searching-rules`

Update API path.

---

src/components/projects/edit_pipeline/product_pipeline/pipeline.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

webhook params add ’productName‘

webhook params add ’productName‘

---

src/components/projects/env/inner_env/create_env_detail.vue

use customise namespace while create env

use customise namespace while create env

---

src/components/projects/service_mgr/helm/code.vue

- hidden useless save button in helm services page
How it Works:

Hidden useless save button in helm services page

---

src/components/projects/env/outer_env/home.vue

Order envs by name.

---

src/components/setting/cluster/manage.vue

Set default method to deployment in cluster managent.

---

src/components/projects/env/env_detail/env_detail_comp.vue

production env add hosting config button

production env add hosting config button

---

src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/service_mgr/helm/components/common/chart_repo.vue
src/components/projects/service_mgr/helm/components/common/repo.vue
src/components/projects/service_mgr/helm/components/common/template_repo.vue
src/components/projects/service_mgr/helm/components/helm/help.vue
src/components/projects/service_mgr/helm/components/helm/match_rule.vue
src/components/projects/service_mgr/helm/components/helm/values.vue

Optimize helm style and desc

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/common/hosting/runWorkflow.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/hosting/serviceModules.vue
src/components/projects/detail_ope/create.vue
src/components/projects/env/hostEnv/editExternalConfig.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/guide/host/components/step.vue

Optimized the interface

---

src/components/projects/service_mgr/helm/components/helm/match_rule.vue

update demo for custom image

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

Fix webhook bug

---

src/components/projects/detail_ope/home.vue
src/components/projects/service_mgr/helm/components/common/repo.vue

Helm templates diaabled.
How it Works:

Helm templates diaabled.

---

src/components/projects/common/not_k8s/add_host.vue
src/components/setting/host/manage.vue

Fix private key show error in host management.
How it Works:

Fix private key show error in host management

---

src/components/projects/pipeline/workflow_multi_task_detail.vue

Show env variables in pipeline detail page
How it Works:

Show env variables in pipeline detail page

---

src/components/projects/detail_ope/home.vue
src/components/projects/service_mgr/helm/components/common/repo.vue

Reverts koderover/zadig-portal#123

Revert "Helm templates disabled."

---

src/api/index.js
src/components/projects/chart_temp/chart/index.vue
src/components/projects/common/codemirror.vue
src/components/projects/common/import_values/index.vue
src/components/projects/common/import_values/value_repo.vue
src/components/projects/detail_ope/home.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/common/git_repo.vue
src/components/projects/service_mgr/helm/components/common/repo.vue
src/components/projects/service_mgr/helm/components/common/update_helm_env.vue
src/components/projects/service_mgr/helm/components/helm/values.vue

Helm env support default variable

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/detail_ope/create.vue

add customize imageName and tarName

add customize imageName and tarName

---

src/api/index.js
src/components/projects/chart_temp/chart/import_chart.vue
src/components/projects/common/import_values/value_repo.vue
src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/common/template_repo.vue
src/components/projects/service_mgr/helm/components/common/template_repo/import_values.vue
src/components/projects/service_mgr/helm/components/common/template_repo/repertory.vue

Support import multi services for template repo
How it Works:

Support import multi services for template repo

---

src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue

Update delete desc by external project
How it Works:

Update delete desc by external project

---

src/router/index.js

fix route error

---

package.json
src/api/index.js
src/common/vue_sse/index.js
src/components/entry/home/topbar.vue
src/components/entry/login.vue
src/components/profile/manage.vue
src/components/setting/integration/account.vue
src/components/setup/admin.vue
src/components/users_mgr/users/manage.vue
src/main.js
src/mobile/profile.vue
src/store/modules/login.js
src/utilities/utilities.js
yarn.lock

Refactor user mangement

---

src/api/index.js
src/components/users_mgr/users/editUserRole.vue
src/components/users_mgr/users/manage.vue

Add role binding to user management.

Add role binding to user management.

---

src/api/index.js
src/components/profile/manage.vue
src/components/projects/service_mgr/k8s/service_aside.vue

Change Profile API.
How it Works:

Change Profile API.

---

src/components/projects/env/env_detail/env_detail_comp.vue

- fix the services sum show error in env
How it Works:

Fix the services sum show error in env

---

dex-site/web/static/main.css
dex-site/web/templates/error.html
src/components/users_mgr/users/manage.vue

Add 'sortBy' to user list. 

---

src/components/projects/template_lib/index.vue

Reorganize template library according to priority.

template lib sequence update

---

src/api/index.js
src/components/entry/components/forgetPassword.vue
src/components/entry/login.vue
src/components/users_mgr/users/manage.vue

Supports reset password.

---

src/components/projects/detail_ope/home.vue
src/router/index.js

the rest of https://github.com/koderover/zadig-portal/pull/183

display K8s YAML first when enter template page

---

src/components/projects/guide/k8s/container/service_editor.vue
src/components/projects/service_mgr/k8s/service_editor.vue

Fix update env button cant use after import a template service
How it Works:

Fix update env button cant use after import a template service

---

src/api/index.js
src/components/common/test_trigger.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue
src/components/projects/test/common/function/function_detail.vue

- webhook add branch regular expression
- validate form
How it Works:

WIP：Webhook add branch regular expression

---

src/components/projects/template_lib/chart_templates/aside.vue

hide the reference list of helm chart template temporarily

---

src/components/projects/build/config_detail.vue
src/components/projects/service_mgr/common/build.vue

fix dockerfile origin

---

src/api/index.js
src/components/projects/template_lib/k8s_templates/file_aside.vue
src/components/projects/template_lib/k8s_templates/file_editor.vue
src/components/projects/template_lib/k8s_templates/index.vue

Fix variables parsing problem.
- Using API to parse k8s variables.
- Real-time monitoring of variables.
How it Works:

Fix variables parsing problem in k8s templates.

---

src/components/common/test_trigger.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

fix bug by webhook add branch regular expression
update code structure
How it Works:

fix bug by webhook add branch regular expression

---

src/components/projects/guide/helm/runtime.vue

fix wrong info in helm chart onboarding

---

src/api/index.js

fix redirect

---

src/components/projects/common/hosting/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

- Supports dockerfile templates in helm.
- Supports dockerfile templates in hosting.

Supports dockerfile templates in helm and hosting.

---

config/index.js
src/api/index.js
src/components/projects/env/service_detail/container_log.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_artifact_deploy.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/mobile/pipelines/task_detail_build.vue

Replace productName in query string
How it Works:

Replace productName in query string

---

src/components/projects/detail_ope/create.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/users_mgr/users/manage.vue
yarn.lock

- Change registry to registry.npmmirror.com.
- Clean debug addr. 
- Replace productName in query string. 
- Change user_ids to admins. 
- Fix delete user error. 
How it Works:

Multiple changes.

---

src/components/projects/common/hosting/runWorkflow.vue

- fix external project onboarding 
How it Works:

fix external

---

src/components/entry/home/topbar.vue
src/components/users_mgr/users/manage.vue

Fix username display.

---

src/api/index.js
src/components/projects/service_mgr/common/service_tree.vue
src/components/projects/service_mgr/k8s/service_aside.vue
src/components/setting/integration/code.vue

Change API route.

---

src/components/setting/integration/account.vue

- Update github form.
- Adjusting LDAP Settings.

Optimize user account management.

---

src/components/entry/home/sidebar.vue
src/components/setting/integration/account.vue

- Supports Microsoft Active Directory in accounts.
- Change sidebar's route.

Supports Microsoft Active Directory in accounts.

---

src/api/index.js
src/components/entry/login.vue
src/components/setting/integration/account.vue

- Check connectors when login.
- Fix validation rule.

Check connectors when login.

---

src/components/projects/common/hosting/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

FIx orgId undefined.

---

src/components/entry/home.vue

fix external link style error
How it Works:

fix external link style error

---

dex-site/Dockerfile
dex-site/web/templates/header.html
src/components/entry/components/signUp.vue
src/components/setting/auditlog/manage.vue
src/components/setting/integration/account.vue

Multiple bug fixed.
- Fix product_name in query. 
- Fix typo. 
- Add validation to OAuth and LDAP. 
- Fix update OAuth bug. 
- Fix product_name in query when searching log.
How it Works:

Multiple bug fixed.

---

src/components/entry/home.vue
src/components/entry/home/announcement.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/rbac/member.vue
src/components/projects/service_mgr/service_k8s.vue
src/main.js
src/utilities/utilities.js

Show notification when smtp isn't configured.

Show notification when smtp isn't configured.

---

src/components/projects/detail_ope/home.vue

Fix project’s env is empty in list mode.

Fix project’s env is empty in list mode.

---

src/api/index.js
src/components/projects/delivery/version/container/run_workflow.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/edit_pipeline/product_pipeline/pipeline.vue
src/components/projects/env/env_detail/run_workflow.vue
src/components/projects/env/inner_env/service_detail.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/not_k8s/not_k8s_delivery.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_list/pipeline_row.vue
src/components/projects/pipeline/workflow_list/virtual_list_item.vue
src/components/projects/pipeline/workflow_multi_detail.vue
src/mobile/pipelines/detail.vue
src/mobile/pipelines/pipelines.vue
src/mobile/pipelines/run_workflow.vue
src/store/modules/workflow_list.js
src/utilities/virtual_scroll_list_mixin.js

- Refactoring for get workflows.
- Fix projectName not present.
How it Works:

Refactoring for workflows list.

---

src/api/index.js
src/components/common/artifact_download.vue
src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/inner_env/service_config.vue
src/components/projects/env/service_detail/container_log.vue

- Fix delete project API.
- Fix download testfile. 
- Clean useless code.

Multiple bugs fixed.

---

src/api/index.js
src/components/projects/delivery/home.vue
src/components/projects/edit_pipeline/product_pipeline/pipeline.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/basic_info.vue
src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_list/virtual_list_item.vue
src/components/projects/pipeline/workflow_multi_detail.vue
src/router/index.js
src/store/modules/product_list.js

Change API route
How it Works:

Change API route

---

src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_list/virtual_list_item.vue

Add projectName to query when copy workflow

Add projectName to query when copy workflow

---

src/api/index.js
src/components/projects/delivery/version/detail.vue
src/components/projects/delivery/version/index.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/test.vue

Add projectName to query.

---

src/components/projects/common/hosting/serviceBuild.vue

- fix host build style
How it Works:

fix build style

---

src/components/projects/detail_ope/detail.vue

Change prop 'admin' to 'project-admin' when checking project's admin.

Change 'admin' to 'project-admin'.

---

src/components/users_mgr/users/manage.vue

Add new column to user list.

---

src/components/projects/pipeline/common/run_workflow.vue

Signed-off-by: ming <wbjxxzx@163.com>
Issue Number: close #237

Workflow manual trigger enhencement：when multi-selecting the service, retain the current search term after selecting an option

---

src/components/setting/integration/account.vue

Remove 'insecureSkipVerify' in OAuth configuration.
Default configuration:
```
insecureNoSSL: true,
insecureSkipVerify: true
```

Remove 'insecureSkipVerify' in OAuth configuration.

---

src/components/entry/login.vue

Fix idtoken typo.
How it Works:

Fix idtoken typo.

---

src/components/setting/integration/mail.vue

Don’t show name and subject in SMTP configuration.
How it Works:

Don’t show 'name' and 'subject' in SMTP configuration.

---

src/api/index.js
src/components/entry/login.vue
src/components/users_mgr/users/manage.vue

Add registration switch in user management.
How it Works:
Checking registration  switch status when sign into system.

Add registration switch in user management.

---

src/api/index.js
src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/env/hostEnv/editHosService.vue

Add projectName to hosting environment API.
How it Works:

Add projectName to hosting environment API.

---

src/components/setting/integration/code.vue

Data structure changes:
- applicationId -> application_id
- clientSecret -> client_secret
- accessToken -> access_token

Fix data structure in code integration page.

---

src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/editor/order.vue

Add service to second order in orchestration mode.
How it Works:

Add service to second order in orchestration mode.

---

src/components/setting/cluster/manage.vue

The link of cluster management is wrong

fix cluster manage link

---

src/api/index.js
src/components/setting/integration/mail.vue

Fix SMTP API route.
How it Works:
`/api/v1/emails/internal/host` will return unmask password.

Fix SMTP API route.

---

src/components/projects/env/env_detail/env_detail_comp.vue

- delete jump detail page when access env error
How it Works:

remove jump when env error

---

src/api/index.js

Change user deletion API route.
Delete `/api/v1/users/:uid` -> ` /api/v1/picket/users/:uid`

Change user deletion API route.

---

src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/service_mgr/service_k8s.vue

Change 'env_name' to 'name'

---

src/components/entry/login.vue

Add fallback for no connectors.
How it Works:

Add fallback when no connector is available.

---

src/components/entry/login.vue

Switch to the login page after registration is complete
- Add registration checking 
- Use new afterSignUp function
How it Works:

Switch to the login page after registration is complete

---

package.json
src/components/projects/build/build_env.vue
src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/service_mgr/service_pm.vue
src/components/projects/test/common/function/function_detail.vue

- build step support custom resource
How it Works:

Build support custom resource

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

Fix show envs in trigger.

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/setting/cluster/manage.vue
src/components/setting/integration/account.vue
src/utilities/utilities.js

Fix preferredUsernameAttr missing when create  LDAP  configuration.
How it Works:

Fix preferredUsernameAttr missing when create  LDAP  configuration.

---

src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/editor/order.vue

Reverts koderover/zadig-portal#244

Revert "Add service to second order in orchestration mode."

---

src/common/task_list.vue
src/components/projects/pipeline/workflow_list/pipeline_row.vue
src/components/projects/pipeline/workflow_list/virtual_list_item.vue

- Show repo info in task list.
- Show description in workflow list.

Show repo info in task list.

---

src/components/projects/rbac/member.vue
src/components/users_mgr/users/manage.vue

Remove default line-height in username

Fix username's line-height in user list.

---

src/common/task_list.vue
src/components/projects/pipeline/workflow_list/pipeline_row.vue
src/components/projects/rbac/member.vue
src/components/users_mgr/users/manage.vue

- Add static width to desc in workflow row.
- Show repo name in workflow tasklist

Add static width to desc in workflow row. 

---

src/common/task_list.vue
src/components/projects/pipeline/workflow_list/pipeline_row.vue

- Add static width to desc in workflow row.
- Show repo name in workflow tasklist

Add static width to desc in workflow row.

---

src/components/projects/test/common/function/function_detail.vue

Signed-off-by: huangzexiong <huangzexiong@52tt.com>
Issue Number: https://github.com/koderover/zadig/issues/694
What's Changed: src/components/projects/test/common/function/function_detail.vue
How it Works:

add params $SERVICES

---

src/api/index.js
src/assets/css/common/scroll-bar.less
src/components/projects/build/build_env.vue
src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/test/common/function/function_detail.vue
src/components/setting/cluster/manage.vue
src/mobile/pipelines/task_detail_build.vue
src/utilities/utilities.js

- add local cluster and advanced configuration
- build and test can select cluster and namespace
How it Works:

Resource configuration in build and test page

---

src/api/index.js
src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/env/inner_env/service_detail.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/pipeline/common/run_workflow.vue

Environment can select image registry

---

src/common/task_list.vue

- fix pipeline detail show error
How it Works:

Fix pipeline show error

---

package.json
src/utilities/jwt.js
yarn.lock

Parsing bug when decode JWT.
How it Works:

fix:parsing bug when decode JWT.

---

src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/service_detail.vue

- fix projectName undefined
How it Works:

fix projectName undefined

---

src/components/projects/env/inner_env/create_env_detail.vue

- update imagePullSecret to default-registry-secret
How it Works:

update imagePullSecret to default-registry-secret

---

src/components/projects/rbac/home.vue

Style variable duplicate in project's rbac page.
How it Works:
Change 'project-home' to 'project-rbac-container'

fix(style):style variable duplicate.

---

src/components/projects/build/build_env.vue

- fixed select namespace invalid
How it Works:

fix(build): fixed select namespace invalid

---

src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/service_detail/container_log.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_test.vue
src/components/projects/test/common/function/container/task_detail_test.vue

fix(api):fix projectName missing in API.
How it Works:

fix(api):fix projectName missing in API.

---

src/common/repo_select.vue

-  can't select repo name after console error
How it Works:

fix(repo): can't select repo name after console error

---

src/components/projects/test/common/function/container/function_test_list.vue

Show description in testcase list.
src/components/projects/test/common/function/container/function_test_list.vue

feat(test):show description in testcase list.

---

src/components/projects/delivery/version/helm/detail.vue

- helm version detail can jump artifact page
How it Works:

feat(version): jump artifact page

---

src/api/index.js

Signed-off-by: fansi <fansi404@koderover.com>
How it Works:

fix missing projectName for helm api

---

src/api/index.js
src/components/projects/delivery/version/helm/create_version.vue
src/components/projects/delivery/version/helm/create_version/config.vue
src/components/projects/delivery/version/helm/create_version/push.vue
src/components/projects/delivery/version/helm/detail.vue

- add projectName query about creating helm version
How it Works:

feat(api): add projectName query

---

src/components/projects/service_mgr/common/add_code.vue
src/components/setting/integration/code.vue

Dependent on:https://github.com/koderover/zadig/pull/725
Optimize the code integration query.
Change API to new path：
`/api/v1/codehosts/${codehostId}/auth?redirect=${redirectUrl}`

feat(codehost):Optimize the code integration API query.

---

src/components/projects/rbac/add-role-bind.vue

Remove name when create role binding.
How it Works:

fix(rbac):remove name when create role binding.

---

src/components/projects/env/createHelmEnv.vue
src/components/projects/env/inner_env/create_env_detail.vue

Add delay to solve the permission synchronization problem.
Default: 5000ms

fix(env):add delay to solve the permission synchronization problem.

---

package.json
src/utilities/jwt.js
yarn.lock

Cherry pick for https://github.com/koderover/zadig-portal/pull/277/

fix:parse bug when decode JWT.

---

src/api/index.js
src/components/common/artifact_download.vue
src/components/projects/delivery/version/index.vue
src/components/projects/env/env_detail/env_detail_comp.vue

add projectName to API query.
- /api/aslan/project/products/${projectName}
- /api/aslan/testing/workspace/workflow/${workflowName}/taskId/${taskId}?dir=${dir}
- /api/aslan/workflow/v2/tasks/workflow/${this.workflowName}/taskId/${this.taskId}?token=${token}

fix(permission):add projectName to API query.

---

src/api/index.js

fix: update project_name to projectName

fix: update project_name to projectName

---

src/api/index.js

- fix: add project_name for backend

fix: add project_name for backend

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/artifact_deploy.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/build_deploy.vue

style: add show or hidden tooltip

---

src/components/projects/env/env_detail/env_detail_comp.vue

fix: delete namespace in default registry api

fix: delete namespace in default registry api

---

src/api/index.js
src/components/common/artifact_download.vue
src/components/projects/delivery/version/index.vue
src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/service_detail/container_log.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_test.vue
src/components/projects/test/common/function/container/task_detail_test.vue
src/mobile/pipelines/task_detail_build.vue

Cherry pick:
- https://github.com/koderover/zadig-portal/pull/298
- https://github.com/koderover/zadig-portal/pull/290

fix(api):fix projectName missing in API. #290 #298

---

src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue

Compatible with the field product_feature
How it Works:

fix(project):compatible with the field product_feature

---

src/components/projects/delivery/version/k8s/detail.vue

- fix yaml version show error
- hide delivery list

fix: yaml version show error

---

yarn.lock

chore:update caniuse package.

---

src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

- webhook trigger add yaml mode

feat(trigger): add yaml webhook trigger

---

src/components/entry/home/topbar.vue

feat: add docs link about word pr

feat: add docs link about word pr

---

src/assets/css/common/build-row.less
src/components/common/workflow_build_rows.vue
src/components/projects/common/hosting/runWorkflow.vue
src/components/projects/edit_pipeline/product_pipeline/container/workflow_args.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue
src/components/projects/env/env_detail/run_workflow.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/not_k8s/not_k8s_delivery.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_multi_detail.vue
src/mobile/pipelines/detail.vue
src/mobile/pipelines/pipelines.vue
src/mobile/pipelines/run_workflow.vue

Refactoring the workflow startup section,make it fast and more clean.

refactor(workflow): optimize workflow initiation process.

---

src/api/index.js
src/assets/css/component/env-detail.less
src/components/projects/common/not_k8s/add_host.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/components/pmHostList.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/guide/not_k8s/container/step_not_k8s.vue
src/components/projects/guide/not_k8s/not_k8s_config.vue
src/components/projects/guide/not_k8s/not_k8s_deploy.vue
src/components/projects/guide/not_k8s/not_k8s_info.vue
src/components/projects/service_mgr/service_pm.vue
src/mobile/envs/env_detail.vue
src/utilities/word_translate.js

feat(host):supports edit hosts in service list.

---

src/components/common/workflow_build_rows.vue
src/components/projects/pipeline/common/run_workflow.vue

fix the problem that the test repo is not available at startup
How it Works:

fix(workflow):fix the problem that the test repo is not available at startup

---

src/components/projects/env/inner_env/create_env_detail.vue

supports deploy pm environment by labels.

feat(pm):supports deploy pm environment by labels.

---

src/components/projects/pipeline/common/run_workflow.vue

filter the targets only when build exists.

fix(workflow):filter the targets only when build exists.

---

src/components/projects/service_mgr/helm/code.vue
src/components/projects/service_mgr/helm/components/common/git_repo.vue
src/components/projects/service_mgr/helm/components/common/template_repo.vue
src/components/projects/service_mgr/helm/components/editor/folder.vue
src/store/modules/service_manage.js

- display values.yaml content when expend a helm service
- expend the service which is added or updated

feat(helm): optimize helm service interaction

---

src/api/index.js
src/components/projects/common/hosting/runWorkflow.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/not_k8s/not_k8s_delivery.vue
src/components/projects/pipeline/workflow_list.vue

Change API route in common workflow.
Using `/api/aslan/workflow/v3` when get common workflows in project

fix(permission):change API route in common workflow.

---

src/components/projects/delivery/version/helm/create_version/config.vue
src/components/projects/delivery/version/helm/create_version/push.vue
src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

- chart version format when create a helm version
- can't select cluster when create a host project
- can select all projects when create or edit cluster

fix: 1.8.0 test

---

src/components/entry/home/topbar.vue
src/components/setting/integration/other.vue

Problem Summary: Some href links return 404
What's Changed: Fix the link 404 error

fix: document href 404

---

src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

- adjust cluster advanced config 
- move cluster operation to advanced mode and default select all clusters

fix:Optimize cluster management

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/detail_ope/create.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

- fix host project show registry
- fix external project create environment error
- fix show error when add a build
- host project can select cluster

fix: host project show registry and external project create environment error

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/detail_ope/create.vue
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/pipeline/common/run_workflow.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/345

fix: cherry-pick 345

---

src/directive/index.js

fix import path.
How it Works:

fix:fix import path.

---

src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/348

fix: cherry-pick  348

---

src/components/projects/common/not_k8s/not_k8s_form.vue

chore: delete useless code

---

src/components/projects/common/not_k8s/not_k8s_form.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/352

chore: delete useless code - cherry-pick 352

---

src/components/entry/home/topbar.vue

Problem Summary: Glossary document is imcomplete for now. 
What's Changed: Hide the glossary href link

hide glossary temporarily

---

src/components/entry/home/topbar.vue

Problem Summary: Glossary document is imcomplete for now. 
What's Changed: Hide the glossary href link

feat: hide glossary temporarily

---

src/components/projects/common/not_k8s/not_k8s_form.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/353

fix: show error after switch host service - cherry-pick 353

---

src/components/projects/common/not_k8s/not_k8s_form.vue

fix: show error after switch host service

fix: show error after switch host service

---

src/components/projects/pipeline/workflow_list.vue

feat(workflow):disable common workflow.

---

src/components/projects/detail_ope/detail.vue

fix layout of project's item.
How it Works:

fix(layout):fix layout of project's item.

---

src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/360

fix: delete all item when edit cluster - cherry-pick 360

---

src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

- delete all clusters item when create project
- delete all projects item when create or edit cluster

fix(1.8.0): delete all item when edit cluster

---

src/components/projects/pipeline/workflow_common_task_detail.vue
src/components/projects/pipeline/workflow_common_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_test.vue
src/components/projects/test/common/function/container/task_detail_test.vue
src/mobile/pipelines/run_workflow.vue
src/mobile/pipelines/task_detail_build.vue

fix typo
- change '构建信息' to '代码信息'
- remove '测试任务'

feat(typo):fix typo

---

src/components/projects/build/build_env.vue

fix: don't request namespace if has not cluster

fix: don't request namespace if has not cluster

---

src/components/projects/build/build_env.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/365

fix: don't request namespace if has not cluster - cherry-pick 365

---

src/components/projects/common/not_k8s/not_k8s_form.vue

show env configuration in onboarding.

feat(pm):show env configuration in onboarding.

---

src/components/projects/env/inner_env/create_env_detail.vue

fix $router function is undefined.
How it Works:

fix(env):fix $router function is undefined.

---

src/components/projects/pipeline/workflow_list.vue

Reverts koderover/zadig-portal#356
Signed-off-by: fansi404 fansiqiong@koderover.com

Revert "feat(workflow):disable common workflow."

---

src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

- can clear all project items when edit cluster
- can clear cluster items when create project

fix: clear clusters or projects

---

src/components/projects/detail_ope/create.vue
src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/372

fix: clear clusters or projects - cherry-pick 372

---

src/components/projects/common/hosting/addHostEnv.vue

the project can't use local cluster, request namespace api error when create a environment

fix: api error when external project create a env

---

src/components/projects/common/hosting/addHostEnv.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/374

fix: api error when external project create a env - cherry-pick 374

---

src/components/setting/cluster/manage.vue

style: hidden other project in edit cluster

style: hidden other project in edit cluster

---

src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/376

style: hidden other project in edit cluster - cherry-pick 376

---

src/components/projects/common/not_k8s/not_k8s_form.vue

fix(pm):fix refs is undefined.

fix(pm):fix refs is undefined.

---

src/components/projects/common/not_k8s/not_k8s_form.vue

cherry-pick:pick 362 378

---

src/components/setting/cluster/manage.vue

fix: add clear projects button

fix: add clear projects button

---

src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/380

fix: add clear projects button - cherry-pick 380

---

src/components/projects/env/createHelmEnv.vue

fix: create helm environment error if has not default registry

fix: create helm environment error if has not default registry

---

src/components/projects/env/createHelmEnv.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/382

fix: create helm environment error if has not default registry - cherry-pick 382

---

src/components/projects/env/createHelmEnv.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/guide/helm/runtime.vue

fix: set cluster to non-require

fix: set cluster to non-required

---

src/components/projects/env/createHelmEnv.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/guide/helm/runtime.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/384

fix: set cluster to non-required - cherry-pick 384

---

src/components/projects/pipeline/workflow_list.vue

feat(workflow):enable common workflow.

---

src/components/projects/pipeline/workflow_multi_task_detail.vue

- jump version detail page error from the product workflow detail page

fix: jump version detail error

---

src/mobile/envs/env_detail.vue
src/mobile/envs/envs.vue
src/mobile/envs/service_detail.vue
src/mobile/pipelines/pipelines.vue

Fix errors in mobile page.
How it Works:

fix(mobile):fix errors in mobile page.

---

src/directive/permission/hasPermi.js

chore:disable unused code.

---

src/components/projects/common/integration_registry.vue
src/components/setting/registry/manage.vue

Preserve default configuration when switching provider:

fix:preserve default configuration when switching provider

---

src/App.vue
src/assets/css/component/subtask.less
src/common/terminal.vue
src/common/xterm_debug.vue
src/common/xterm_log.vue
src/common/xterm_log_container.vue
src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/service_detail/container_log.vue
src/components/projects/test/common/function_test_case.vue

- declare the scrollbar style in app.vue 
- add Consolas for xterm log

fix(style):declare the scrollbar style in app.vue

---

src/components/projects/common/hosting/serviceBuild.vue

fix scroll bug in service page.

fix(style):fix scroll bug in service page.

---

src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/edit_pipeline/common_pipeline/switch_tab/build.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue

fix(typo):change 'REPONAME' to 'REPO'.

---

src/components/common/workflow_build_rows.vue
src/components/common/workflow_test_rows.vue
src/components/projects/build/config_detail.vue
src/components/projects/build/env_variable.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/test.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/test/common/function/function_detail.vue

- build and test support environment variable of array type
- support choice type when workflow add test stage
- can select var when run or clone workflow

feat: build and test support environment variable of array type

---

src/api/index.js
src/common/repo_select.vue

Fix the problem of branch searching
For GitLab：
Remote branch search does not work，only 100 data items are returned by default
- Show more data
- Support remote fuzzy search
How it Works:

fix(repo_select):fix the problem of gitlab branch searching

---

src/components/projects/build/env_variable.vue

fix: clear value when delete a used choice item

fix: clear value when delete a used item

---

src/components/setting/integration/account.vue
src/components/setting/integration/home.vue

chore: update user account to account system

chore: update user account to account system

---

src/components/setting/integration/account.vue

Problem Summary: update user account to account system
What's Changed: update user account to account system

chore: change user account to account system

---

src/api/index.js
src/common/task_list.vue
src/components/projects/pipeline/workflow_multi_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/filterStatus.vue

product workflow can filter data

feat: product workflow can filter data

---

src/api/index.js
src/common/repo_select.vue
src/components/projects/build/build_env.vue
src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/test/common/function/function_detail.vue
src/components/setting/cluster/manage.vue

Fix the problem that the repo_name is empty when manually creating branches.
The repo_name will be cleared when the branch is created.
Influence of scope:
- Non GitLab Repos

fix(repo_select):fix the problem that the repo_name is empty when manually creating branches.

---

src/api/index.js
src/common/repo_select.vue
src/components/projects/build/build_env.vue
src/components/projects/build/config_detail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/test/common/function/function_detail.vue
src/components/setting/cluster/manage.vue

Reverts koderover/zadig-portal#412

Revert "fix(repo_select):fix the problem that the repo_name is empty when manually creating branches."

---

src/common/repo_select.vue

cherry-pick:#424

---

src/components/projects/edit_pipeline/product_pipeline/pipeline.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/basic_info.vue

feat: expand image rollback policy

feat: expand image rollback policy

---

src/components/projects/build/config_detail.vue
src/components/projects/build/env_variable.vue
src/components/projects/common/hosting/build.vue
src/components/projects/common/not_k8s/not_k8s_form.vue
src/components/projects/service_mgr/common/build.vue
src/components/projects/service_mgr/helm/components/common/build.vue
src/components/projects/test/common/function/function_detail.vue

fix: add environment variable valid

fix: add environment variable valid

---

src/components/common/test_trigger.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

fix: trigger methods show consistent

fix: trigger methods show consistent

---

src/components/projects/pipeline/common/repoJump.vue
src/components/projects/pipeline/workflow_common_task_detail.vue
src/components/projects/pipeline/workflow_common_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_test.vue
src/mobile/pipelines/task_detail_build.vue

feat: build info show tag

---

src/api/index.js
src/assets/css/component/insight-charts.less
src/components/entry/home/sidebar.vue
src/components/insight/build/averageDuration.vue
src/components/insight/build/daliyFeq.vue
src/components/insight/build/health.vue
src/components/insight/build/longestBuilds.vue
src/components/insight/build/recentBuilds.vue
src/components/insight/build/trend.vue
src/components/insight/build/view.vue
src/components/insight/home.vue
src/components/insight/service/deploy.vue
src/components/insight/service/deploySummary.vue
src/components/insight/service/failure.vue
src/components/insight/service/health.vue
src/components/insight/service/view.vue
src/components/insight/test/averageDuration.vue
src/components/insight/test/deploy.vue
src/components/insight/test/health.vue
src/components/insight/test/testCases.vue
src/components/insight/test/trend.vue
src/components/insight/test/view.vue
src/router/index.js

feat:add insights dashboard.

---

src/api/index.js
src/components/entry/home/topbar.vue
src/components/statistics/common/barChart.vue
src/components/statistics/constainer/build.vue
src/components/statistics/constainer/deploy.vue
src/components/statistics/constainer/test.vue
src/components/statistics/view.vue
src/router/index.js

Add system statistics page.
How it Works:

feat(statistics):add system statistics page.

---

src/components/projects/env/env_detail/env_detail_comp.vue

pref: optimize environment request data rate

pref: optimize environment request data rate

---

src/components/projects/service_mgr/helm/components/common/git_repo.vue
src/components/projects/service_mgr/helm/components/common/template_repo.vue

fix: show error when add an incorrect helm service

fix: show error when add an incorrect helm service

---

src/components/projects/service_mgr/helm/components/common/git_repo.vue
src/components/projects/service_mgr/helm/components/common/template_repo.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/432

cherry-pick 432

---

src/components/setting/registry/manage.vue

fix: reset image registry logic

fix: reset image registry logic

---

src/components/setting/registry/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/430

cherry-pick 430

---

src/components/projects/env/inner_env/home.vue

fix: jump error when delete environment

fix: jump error when delete environment

---

src/components/projects/env/inner_env/home.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/436

cherry-pick 436

---

src/api/index.js
src/components/insight/build/recentBuilds.vue
src/components/insight/build/view.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/439

cherry-pick 439

---

src/api/index.js
src/components/insight/build/recentBuilds.vue
src/components/insight/build/view.vue

fix: recent ten builds show data error

fix: recent ten builds show data error

---

src/components/statistics/constainer/build.vue
src/components/statistics/constainer/deploy.vue

fix: automated build and deploy show error

fix: automated build and deploy show error

---

src/components/statistics/constainer/build.vue
src/components/statistics/constainer/deploy.vue

cherry-pick  https://github.com/koderover/zadig-portal/pull/441

cherry-pick 441

---

src/components/projects/pipeline/workflow_list.vue

chore: hidden common workflow

---

src/components/projects/delivery/version/k8s/detail.vue

fix: version release error

---

src/components/projects/delivery/version/k8s/detail.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/444

cherry-pick  444

---

src/api/index.js
src/assets/css/component/service-mgr.less
src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/env/inner_env/home.vue
src/components/projects/service_mgr/common/service_tree.vue
src/components/projects/service_mgr/service_k8s.vue

feat: k8s environment can use existed namespace

feat: k8s environment can use existed namespace

---

src/components/setting/cluster/manage.vue

Problem Summary: the namespace of connected is wrong
What's Changed: rename the namespace of connected cluster

fix: misspelling

---

src/components/entry/home/sidebar.vue
src/components/insight/home.vue

Fix insight sidebar activation issues.
- Sidebar is inactive when switching to other insight panels.
- After refreshing the page, the tab is not updated to the current panel.
Activate tab based on route when page mounted.

fix:fix insight sidebar activation issues.

---

src/api/index.js

- can't create environment in onboarding

fix: add auto params in put and post api

---

src/components/entry/home/topbar.vue

Supports searching projects by name.

feat(topbar):supports searching projects by name.

---

src/components/projects/build/config.vue
src/components/projects/build/config_detail.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/env/inner_env/home.vue
src/components/projects/pipeline/workflow_common_detail.vue
src/components/projects/pipeline/workflow_common_task_detail.vue
src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_multi_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail.vue
src/components/projects/rbac/home.vue
src/components/projects/test/function/function.vue
src/components/projects/test/function/functionTaskDetail.vue
src/components/projects/test/function/function_detail.vue
src/components/projects/test/function/function_summary.vue
src/components/projects/test/report/test_case.vue
src/components/projects/test/report/workflow_multi_test_case.vue
src/components/quality_manage/tests/first.vue

Remove unused subSidebar code.

chore:remove unused subSidebar code.

---

src/components/entry/home/subTopbar.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/detail_ope/view.vue
src/components/projects/pipeline/workflow_list.vue
src/components/projects/pipeline/workflow_list/productRow.vue
src/components/projects/rbac/home.vue
src/components/projects/test/function/function_detail.vue

style: change style of subtopbar 

---

src/components/entry/home/sidebar.vue

style:update sidebar items

---

src/components/entry/home.vue
src/components/entry/home/sidebar.vue
src/components/projects/build/config.vue
src/components/projects/env/inner_env/home.vue
src/components/projects/test/common/function/function.vue

- fix color of sidebar link
- fix color of topbar
- fix scroll bug within the project

fix(style):scroll bug within the project.

---

src/components/projects/build/configDetail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/edit_pipeline/common_pipeline/switch_tab/build.vue
src/components/projects/serviceMgr/helm/components/common/build.vue
src/components/projects/test/function/functionDetail.vue
src/router/index.js

- [fix scroll bug in project's build.](https://github.com/koderover/zadig-portal/commit/06abab5168e052b3d6c2348a40e00cdaaccdb227)
- [fix: fix component not found.](https://github.com/koderover/zadig-portal/commit/4d7af071eabf1ae0b698fd1451431f49b279a866)
- [fix:mv build to project's route.](https://github.com/koderover/zadig-portal/commit/fb5fdcda8c2d6b4760db545f3023726a85836964)

fix:fix layout bugs.

---

src/components/projects/build/configDetail.vue
src/components/projects/common/hosting/build.vue
src/components/projects/detail_ope/create.vue
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/serviceMgr/helm/components/common/build.vue
src/components/setting/announcement/manage.vue
src/components/setting/apps/manage.vue
src/components/setting/cluster/manage.vue
src/components/setting/helm/manage.vue
src/components/setting/host/manage.vue
src/components/setting/imgs/manage.vue
src/components/setting/integration/code.vue
src/components/setting/integration/jenkins.vue
src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue

- change typo. 
- fix project details route

fix(style):change style

---

src/components/entry/home/subTopbar.vue

change position of menu item.
How it Works:

fix(subtopbar):change position of menu item.

---

src/components/setting/cluster/manage.vue

- fix: can't deploy if cant access cluster
- fix: prompt only once when switch storage type
- fix: hidden advanced configurations when add a cluster
- fix: add form validation

fix: build cache question

---

src/assets/css/component/insight-charts.less
src/components/insight/build/longestBuilds.vue
src/components/insight/build/recentBuilds.vue
src/components/insight/common/subTopbar.vue
src/components/insight/home.vue
src/components/insight/service/failure.vue
src/components/projects/detail_ope/detail.vue
src/router/index.js

[fix(style):change style of insight.](https://github.com/koderover/zadig-portal/commit/9ecbc4ade8ffaf20a1311f48520db80300c15f73)
How it Works:

fix(style):change style of insight. 

---

src/components/projects/env/env_detail/env_detail_comp.vue
src/components/projects/env/inner_env/create_env_detail.vue
src/components/projects/service_mgr/service_k8s.vue

Problem Summary: The hit info for deploy service in existing namespace is improper.
What's Changed: Update the hit info for deploy service in existing namespace.

fix(typo): update hit

---

src/components/entry/home/sidebar.vue
src/components/setting/apps/manage.vue
src/components/setting/cluster/manage.vue
src/components/setting/config/cache.vue
src/components/setting/config/link.vue
src/components/setting/config/proxy.vue
src/components/setting/helm/manage.vue
src/components/setting/host/manage.vue
src/components/setting/imgs/manage.vue
src/components/setting/integration/account.vue
src/components/setting/integration/code.vue
src/components/setting/integration/external.vue
src/components/setting/integration/github_app.vue
src/components/setting/integration/jenkins.vue
src/components/setting/integration/jira.vue
src/components/setting/integration/mail.vue
src/components/setting/integration/other.vue
src/components/setting/registry/manage.vue
src/components/setting/sidebar.vue
src/components/setting/storage/manage.vue
src/router/index.js

Signed-off-by: lilianzhu <zhujiali@koderover.com>
Problem Summary: update system settings glossary

fix(typo): update system settings banner info

---

src/components/profile/manage.vue

feat(token): add permanent token

feat(token): add permanent token

---

src/components/setting/config/quota.vue

Problem Summary: Update the tooltip info for workflow concurrency setting.
How it Works:

fix(typo): update tooltip info for workflow concurrency setting

---

src/components/delivery/artifacts/index.vue
src/components/delivery/version/detail.vue
src/components/delivery/version/index.vue
src/components/entry/home/sidebar.vue
src/components/insight/build/view.vue
src/components/insight/home.vue
src/components/insight/service/view.vue
src/components/insight/test/view.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/statistics/view.vue
src/components/templateLibrary/chart/index.vue
src/components/templateLibrary/dockerfile/index.vue
src/components/templateLibrary/index.vue
src/components/templateLibrary/k8s/index.vue

- [fix artifact's link.](https://github.com/koderover/zadig-portal/commit/26a048024350dfc414b3760906969bd6fc512a28)
- [fix(breadcrumb):fix breadcrumb's route.](https://github.com/koderover/zadig-portal/commit/1ee9159d71e2faf7835755e450515ad910006395)
- [fix(layout):change sidebar items in setting.](https://github.com/koderover/zadig-portal/commit/294f813ca37590a5f8cfccb35c7be80e277e5914)
- [fix(style):change style of nav-item-label.](https://github.com/koderover/zadig-portal/commit/f5795a30823ee689175920e2a2ab20486036315e)

fix(style):change style of nav-item-label. 

---

src/components/projects/edit_pipeline/product_pipeline/pipeline.vue
src/components/projects/edit_pipeline/product_pipeline/side_menu.vue
src/components/projects/edit_pipeline/product_pipeline/switch_tab/extension.vue
src/components/projects/edit_pipeline/product_pipeline/tab_menu.vue
src/components/projects/pipeline/workflow_multi_task_detail.vue

- product workflow add extension

feat(workflow): product workflow add extension

---

src/assets/css/component/create-version.less
src/assets/css/component/dockerfile-template.less
src/assets/css/component/file-editor.less
src/assets/css/component/k8s-template.less
src/assets/css/component/onboarding-delivery.less
src/assets/css/component/service-editor.less
src/assets/css/component/service-mgr.less
src/assets/css/component/service-tree.less
src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/guide/common/runtime.vue
src/components/projects/guide/helm/basicInfo.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/guide/host/hostConfig.vue
src/components/projects/guide/k8s/basicInfo.vue
src/components/projects/guide/k8s/container/serviceEditor.vue
src/components/projects/guide/pm/config.vue
src/components/projects/guide/pm/deploy.vue
src/components/projects/guide/pm/info.vue
src/components/projects/guide/serviceHelmGuide.vue
src/components/projects/serviceMgr/common/build.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/serviceMgr/servicePm.vue

fix(style): fix style of service manage.

---

src/components/delivery/version/detail.vue
src/components/delivery/version/index.vue
src/router/index.js

fix(route):fix 404 in version page.

---

src/api/index.js
src/assets/css/component/service-tree.less
src/components/projects/guide/k8s/container/serviceEditor.vue
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/templateLibrary/k8s/index.vue

Modify import from template as  a component.

feat:modify import from template as  a component.

---

src/components/projects/workflow/status/container/testStatus.vue
src/components/statistics/constainer/build.vue
src/components/statistics/constainer/deploy.vue
src/components/statistics/constainer/test.vue
src/components/statistics/view.vue

[fix(style):change style of statistics.](https://github.com/koderover/zadig-portal/commit/bb31e52451608566fe889aca377c3dcfc3ed67dc)

fix(style):fix style of page.

---

src/components/projects/serviceMgr/helm/components/helm/matchRule.vue

fix(style): fix style in helm's rule match drawer.

fix(style): fix style in helm's rule match drawer.

---

src/components/entry/home/sidebar.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue

[feat:add policy to helm aside.](https://github.com/koderover/zadig-portal/commit/42c9349e553a8859e7e76c8a53c031d82fcbdaba)

fix(style):fix style of sidebar.

---

src/components/delivery/artifacts/index.vue
src/components/delivery/version/index.vue
src/components/projects/detail_ope/home.vue
src/components/projects/env/inner_env/createEnvDetail.vue
src/components/projects/test/common/function/function.vue
src/components/projects/workflow/commonTaskDetail/build.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/status/status.vue

fix(style):optimize the logic of displaying illustrations when loading

fix(style):optimize the logic of displaying illustrations when loading

---

src/components/entry/home/topbar.vue
src/components/insight/common/subTopbar.vue
src/components/projects/detail_ope/home.vue
src/components/statistics/constainer/test.vue

fix(style):fix style of topbar.

fix(style):fix style of topbar. 

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/basicInfo.vue
src/components/projects/workflow/workflowEditor/productWorkflow/tab.vue

fix(workflow):fix pipelineInfo not found.

---

src/components/projects/common/hosting/runWorkflow.vue
src/components/projects/guide/common/runtime.vue
src/components/projects/guide/common/step.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/k8s/service.vue
src/components/projects/guide/pm/delivery.vue
src/components/projects/guide/pm/deploy.vue

fix(layout):fix style of pm onboarding.

fix(layout):fix style of pm onboarding.

---

src/api/index.js
src/components/common/testTrigger.vue
src/components/profile/manage.vue
src/components/projects/common/pm/pmConfig.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/createEnvDetail.vue
src/components/projects/serviceMgr/serviceK8s.vue
src/components/projects/serviceMgr/servicePm.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/extension.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
src/components/projects/workflow/workflowEditor/productWorkflow/sidebar.vue
src/components/projects/workflow/workflowEditor/productWorkflow/tab.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
src/components/setting/cluster/manage.vue
src/components/setting/config/home.vue
src/components/setting/config/quota.vue

Merge branch main into UI_imporovement.

merge:merge branch main into UI_imporovement.

---

src/components/projects/common/integrationRegistry.vue
src/components/projects/common/pm/addHost.vue
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/setting/cluster/manage.vue
src/components/setting/host/importHosts.vue
src/components/setting/host/manage.vue
src/components/setting/integration/code.vue
src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue

fix(typo): keep typo consistent

---

src/api/index.js
src/components/projects/service_mgr/helm/components/common/chart_repo.vue
src/components/projects/service_mgr/helm/components/common/repo.vue

feat:supports import services from helm chart.

feat:supports import services from helm chart.

---

src/components/setting/cluster/manage.vue

- fix: hide local object storage when editing a non-local cluster

fix: hide local object storage when editing a non-local cluster

---

src/components/projects/build/config.vue

fix(typo):change '修改服务' to '更新服务组件'.

---

src/components/projects/service_mgr/helm/components/common/chart_repo.vue

fix:can't select chart version when reload.

fix:can't select chart version when reload.

---

src/components/projects/service_mgr/helm/components/common/git_repo.vue
src/components/projects/service_mgr/helm/components/common/gitfile_tree.vue

Supports import charts from gerrit.

feat:supports import charts from gerrit.

---

src/common/repo_select.vue
src/components/setting/integration/code.vue

Signed-off-by: Min Min <minmin@koderover.com>
changed enable proxy button position & revert build proxy settings
#502 is a bad way to do per-repository proxy enable and i changed it from backend. So in this PR I revert it back for repo select module
How it Works:

changed enable proxy button position & revert build proxy settings

---

src/components/projects/service_mgr/helm/components/common/git_repo.vue

fix:request repo files when reloading the gerrit service.

fix:request repo files when reloading the gerrit service.

---

src/components/projects/build/config.vue
src/components/projects/guide/helm/basicInfo.vue
src/components/projects/guide/k8s/basicInfo.vue
src/components/projects/guide/pm/info.vue

[fix(route):fix route when exit onbarding.](https://github.com/koderover/zadig-portal/commit/0a455c6494427b78e1071c3253017728a9d839cd)

fix:fix route when exit onbarding

---

src/components/common/testTrigger.vue
src/components/delivery/version/helm/createVersion/config.vue
src/components/delivery/version/helm/createVersion/info.vue
src/components/entry/components/signUp.vue
src/components/entry/home.vue
src/components/entry/home/sidebar.vue
src/components/entry/home/subTopbar.vue
src/components/entry/home/topbar.vue
src/components/profile/manage.vue
src/components/projects/build/configDetail.vue
src/components/projects/common/taskList.vue
src/components/projects/detail_ope/create.vue
src/components/projects/detail_ope/home.vue
src/components/projects/env/inner_env/createEnvDetail.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/projects/test/common/function/container/advancedConfig.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/basicInfo.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
src/components/setting/announcement/manage.vue
src/components/setting/apps/manage.vue
src/components/setting/cluster/manage.vue
src/components/setting/helm/manage.vue

fix: fix ui style

---

src/common/task_list.vue
src/components/projects/pipeline/workflow_multi_task_detail.vue
src/components/projects/pipeline/workflow_multi_task_detail/task_detail_build.vue
src/components/projects/test/common/function/functionTaskDetail.vue
src/utilities/utilities.js

service name support display service components.

feat:service name support display service components.

---

src/components/projects/common/taskList.vue
src/components/projects/test/common/function/functionTaskDetail.vue
src/components/projects/workflow/commonTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail.vue
src/utilities/utilities.js

service name support display service components.

feat:service name support display service components. 

---

src/components/setting/config/quota.vue

Problem Summary: Update wrong hit message for update config setting

fix(typo): update wrong hit message

---

src/api/index.js
src/components/projects/edit_pipeline/product_pipeline/switch_tab/trigger.vue

[fix:fix repo page parameters](https://github.com/koderover/zadig-portal/commit/e68d83eb6f0d887742ae93c8abd3f265ea1cd739)

fix:fix repo page parameters 

---

src/components/delivery/version/container/runWorkflow.vue
src/components/delivery/version/k8s/detail.vue
src/components/entry/home/topbar.vue
src/components/projects/detail_ope/create.vue
src/components/projects/detail_ope/home.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/setting/integration/home.vue

fix(style):fix style of ui.

---

src/components/entry/home.vue
src/components/entry/home/announcement.vue
src/components/entry/home/subTopbar.vue
src/components/projects/detail_ope/home.vue
src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue
src/components/projects/policy/policyDialog.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/helm/matchRule.vue

fix: fix the experience function problem

fix: fix the experience function problem

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue
src/components/setting/integration/account.vue

Problem Summary: fix 404 link + update typo for better understanding

fix(typo): fix 404 link + update typo for better understanding

---

src/components/delivery/version/index.vue
src/components/entry/home/subTopbar.vue
src/components/entry/home/topbar.vue
src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue
src/components/setting/integration/code.vue

fix: fix style issues

---

src/assets/css/theme/button.css
src/assets/css/theme/index.css
src/components/setting/announcement/manage.vue
src/components/setting/apps/manage.vue
src/components/setting/cluster/manage.vue
src/components/setting/config/link.vue
src/components/setting/helm/manage.vue
src/components/setting/host/manage.vue
src/components/setting/imgs/manage.vue
src/components/setting/integration/account.vue
src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue
src/components/setting/users/manage.vue
src/components/templateLibrary/dockerfile/index.vue
src/components/templateLibrary/k8s/index.vue

fix(style):synchronize the button style in the system.

fix(style):synchronize the button style in the system setting.

---

src/assets/css/quote/iconfont.css
src/components/entry/home/common/notification.vue
src/components/entry/home/topbar.vue
src/components/projects/detail_ope/home.vue

- [fix(style):fix style of doc link.](https://github.com/koderover/zadig-portal/commit/d0b9f1e878c2f45dbad69b99be69ac0d9597e9d5)
- [fix(style):fix style of notification.](https://github.com/koderover/zadig-portal/commit/f284e72989fab978ecccdd14030b5ee7cb3133b4)
- [fix(link):change shortcuts in project list.](https://github.com/koderover/zadig-portal/commit/f792b2721fde3fa60a5e9429c35796b4614f0805)

fix(style):fix style issues

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/serviceMgr/k8s/container/policy.vue

fix(typo):change typo of policy.

fix(typo):change typo of policy.

---

src/components/entry/home/common/notification.vue

fix(style):fix style of icon.

---

src/components/projects/service_mgr/helm/components/common/update_helm_env.vue

fix: cannot update environment

fix: cannot update environment

---

src/components/setting/integration/code.vue

Problem Summary: information misrepresented. restore it.

fix(typo): restore the logic of update gerrit config

---

src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/common/chartRepo.vue
src/components/projects/serviceMgr/helm/components/common/repo.vue
src/components/projects/test/common/report/testCase.vue
src/components/projects/test/report/productWorkflowTestCase.vue

[fix:fix import bug in helm service manage.](https://github.com/koderover/zadig-portal/commit/671b75925f27fbc6d77dc2469d8afb9275b8f8f7)

fix:fix import bug in helm service manage. 

---

src/assets/css/common/common.less
src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/build.vue

feat: workflow detail page

---

src/assets/css/component/service-tree.less
src/components/delivery/version/k8s/detail.vue
src/components/entry/home/sidebar.vue
src/components/projects/rbac/member.vue
src/components/projects/workflow/list/productRow.vue
src/components/projects/workflow/status/container/productWorkflowStatus.vue
src/components/projects/workflow/status/container/testStatus.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/artifactDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/buildDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
src/components/setting/sidebar.vue
src/mobile/index.vue
src/mobile/pipelines/pipelines.vue

- [fix(style):change style of workflow stage.](https://github.com/koderover/zadig-portal/commit/d6b3762e925be3d21d0dec545afbfffcf955eab9)
- [fix(style):fix style of sidebar.](https://github.com/koderover/zadig-portal/commit/3a6d809c01edfb56fb62ffe9d211fde0438c3c4a)
- [fix(style):remove custom button style.](https://github.com/koderover/zadig-portal/commit/390b6725887d28bad4945a7ad843f475b6c936d5)
- [fix(color):use global defined color.](https://github.com/koderover/zadig-portal/commit/1f8f263aca8d4310c2ce968c147c4c2cfa881bc3)

fix(style):multiple style bugs is fixed.

---

src/components/projects/detail_ope/home.vue
src/components/projects/guide/pm/config.vue
src/components/projects/serviceMgr/servicePm.vue

- [fix(style)：fix style of illustration in pm.](https://github.com/koderover/zadig-portal/commit/0a5186450d0fae550dc9b56c969dd79044d13006)
- [fix(route):fix project's link in list mode.](https://github.com/koderover/zadig-portal/commit/adec8cea651b4eef942e034efa701811e4371a4b)

fix(style):fix style of illustration in pm.

---

src/assets/css/component/env-detail.less
src/assets/css/component/service-mgr.less
src/components/delivery/version/index.vue
src/components/entry/home.vue
src/components/projects/build/configDetail.vue
src/components/projects/build/envVariable.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/detail_ope/view.vue
src/components/projects/env/createHelmEnv.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/hostEnv/createHostEnv.vue
src/components/projects/env/inner_env/createEnvDetail.vue
src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
src/components/projects/rbac/home.vue
src/components/projects/rbac/policy.vue
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/servicePm.vue
src/components/projects/test/common/function/functionTaskDetail.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/list/productRow.vue
src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/workflowEditor/commonWorkflow/modules/external.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/extension.vue

fix: fix ui

---

src/components/entry/home/sidebar.vue
src/components/projects/serviceMgr/helm/components/common/chartRepo.vue

fix typo when update helm service

fix(typo):fix typo when update helm service. 

---

src/components/projects/serviceMgr/common/importFromTemplate.vue

fix(style):fix style of servicename.

fix(style):fix style of servicename.

---

src/components/projects/detail_ope/components/initEnvDialog.vue
src/components/projects/detail_ope/initialize.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue

fix: key-value pairs cannot be added

fix: key-value pairs cannot be added

---

src/components/projects/build/commonBuild.vue
src/components/projects/build/configDetail.vue
src/components/projects/build/otherSteps.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/common/pm/pmConfig.vue
src/components/projects/common/taskList.vue
src/components/projects/detail_ope/create.vue
src/components/projects/detail_ope/initialize.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/serviceMgr/helm/components/helm/matchRule.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/workflow/list/productRow.vue

fix: optimize ui

---

src/components/projects/policy/home.vue

fix: change button color

---

src/components/entry/components/forgetPassword.vue
src/components/entry/components/signUp.vue
src/components/entry/login.vue

fix(style):change color to themeColor in login page.

fix(style):change color to themeColor in login page.

---

src/components/entry/login.vue

fix(login):revert for checkLogin missing.

fix(login):revert for checkLogin missing.

---

src/components/insight/home.vue
src/components/statistics/view.vue
src/router/index.js

fix(route):fix route in insight.

fix(route):fix route in insight. 

---

src/components/projects/detail_ope/home.vue

fix(route):fix route in project detail page.

fix(route):fix route in project detail page.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

fix(style):fix style of variables table.

fix(style):fix style of variables table.

---

src/components/projects/serviceMgr/k8s/container/policy.vue

fix:fix rules is undefined in policy.

fix:fix rules is undefined in policy.

---

src/components/projects/workflow/status/container/testStatus.vue

fix(route):fix route in testing status page.

fix(route):fix route in testing status page.

---

src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/guide/common/step.vue
src/components/projects/guide/helm/service.vue
src/components/projects/guide/k8s/service.vue
src/components/projects/guide/pm/config.vue
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/serviceK8s.vue

[fix(layout):fix layout in onboarding.](https://github.com/koderover/zadig-portal/commit/37a3ae84d1f4dd3d440791510f302e0a320c0e18)

fix(layout):fix layout in onboarding.

---

src/components/projects/common/pm/pmConfig.vue
src/components/projects/guide/pm/config.vue
src/components/projects/serviceMgr/servicePm.vue

fix(style):fix style in pm config.

fix(style):fix style in pm config.

---

src/api/index.js
src/components/projects/build/advancedConfig.vue
src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue
src/components/projects/test/common/function/function.vue
src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

fix: projectName parameter

---

src/components/entry/home/sidebar.vue
src/components/projects/env/env_detail/envDetailComp.vue

fix:don't show registry config btn in env info.

fix:don't show registry config btn in env info. 

---

src/components/delivery/version/container/runWorkflow.vue

fix:show service module name in runner config.

fix:show service module name in runner config.

---

src/components/projects/serviceMgr/helm/components/helm/help.vue
src/components/projects/serviceMgr/k8s/container/help.vue

What's Changed: Update the tips for creating K8s YAML / Helm Chart service
view(K8s):
view(Helm):

fix(typo): fix typo for K8s/Helm service tips

---

src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
src/components/setting/integration/account.vue

[fix:fix typo and prop in account integration.](https://github.com/koderover/zadig-portal/commit/733adce3ad4010e2c834c8fc4776967ec53eebe3)

fix:fix typo and prop in account integration.

---

src/assets/css/quote/iconfont.css
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/code.vue

fix(icon):change icon

---

src/assets/css/component/service-detail.less
src/assets/css/quote/iconfont.css
src/components/delivery/version/index.vue
src/components/entry/home/topbar.vue

fix project switcher style in topbar.

fix project switcher style in topbar. 

---

src/components/projects/test/common/functionTestCase.vue
src/components/projects/test/common/report/testCase.vue
src/components/projects/test/report/productWorkflowTestCase.vue

fix(style):fix style in testCase page.

fix(style):fix style in testCase page.

---

src/components/delivery/version/index.vue

fix:remove servicename filter in version page.

fix:remove servicename filter in version page.

---

src/components/projects/test/common/function/functionTaskDetail.vue
src/components/projects/workflow/productTaskDetail.vue

fix:fix test report checking logic.

fix:fix test report checking logic.

---

src/components/entry/home/subTopbar.vue

feat:disable common workflow.

---

src/api/index.js
src/components/delivery/version/index.vue
src/components/projects/build/otherSteps.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/common/pm/pmConfig.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/test/common/function/function.vue
src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
src/components/setting/users/manage.vue

- Fix bugs in cloud hosting builds
- add validation for template selection
- new user's form is aligned left and right
- add the ifPassFilter parameter to the associated workflow

fix: fix bugs in cloud hosting builds

---

src/components/projects/common/taskList.vue

fix: webhooks are not handled specially

---

src/components/projects/detail_ope/detail.vue

fix: modify the description of the project details page

---

src/assets/css/component/onboarding-basicInfo.less
src/assets/css/component/onboarding-delivery.less
src/assets/css/theme/index.css
src/components/entry/home/topbar.vue
src/components/projects/guide/common/runtime.vue
src/components/projects/guide/common/step.vue
src/components/projects/guide/helm/basicInfo.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/guide/helm/service.vue
src/components/projects/guide/host/components/step.vue
src/components/projects/guide/k8s/basicInfo.vue
src/components/projects/guide/k8s/service.vue
src/components/projects/guide/pm/config.vue
src/components/projects/guide/pm/container/step.vue
src/components/projects/guide/pm/deploy.vue
src/components/projects/guide/pm/info.vue
src/components/projects/serviceMgr/common/step.vue

[fix(style):fix style in onboarding.](https://github.com/koderover/zadig-portal/commit/d5887af647bbe434d1f713199938d5bad5e57aa0)

fix(style):fix style in onboarding. 

---

src/components/setting/integration/account.vue

fix(style):fix style in account page.

---

src/components/entry/home/sidebar.vue
src/components/statistics/view.vue

fix(icon):update icon.

---

src/assets/css/component/service-help.less
src/assets/css/quote/iconfont.css
src/components/delivery/home.vue
src/components/projects/workflow/status/container/productWorkflowStatus.vue
src/components/statistics/view.vue

- [fix(color):change step to themeColor.](https://github.com/koderover/zadig-portal/commit/ed4e077c696859faeff209c98b618e14f37ccf28)
- [fix(style):using color variable.](https://github.com/koderover/zadig-portal/commit/25159edd0d9b908f7eff7b494d1e539f8c070cf9)
- [fix(style):change style in status page.](https://github.com/koderover/zadig-portal/commit/c90290f86470036c20365d4de66c039f38513bc3)
- [fix(icon):update icon.](https://github.com/koderover/zadig-portal/commit/ae6b04b4b9dcf4ba627dc84895a464b40e416f85)

fix(style):multiple bug fixes.

---

src/assets/css/common/colorEnum.less
src/assets/css/component/service-tree.less
src/assets/css/quote/iconfont.css
src/components/entry/home.vue
src/components/projects/build/buildEnv.vue
src/components/projects/common/pm/pmConfig.vue
src/components/projects/common/taskList.vue
src/components/projects/detail_ope/components/initEnvDialog.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/initialize.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/k8sPmEnv/varList.vue
src/components/projects/policy/policy.vue
src/components/projects/policy/policyDialog.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/editor/order.vue

fix: optimize style

---

src/router/index.js

fix(typo):fix typo in routerList.

fix(typo):fix typo in routerList.

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/guide/common/runtime.vue
src/components/projects/guide/common/step.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/guide/helm/service.vue
src/components/projects/guide/pm/deploy.vue
src/components/projects/serviceMgr/k8s/container/help.vue

- [fix:fix active step in helm onboarding.](https://github.com/koderover/zadig-portal/commit/781a408627f09070eec0ed1340ff0126d513df3b)
- [fix(typo):fix typo in onboarding.](https://github.com/koderover/zadig-portal/commit/f1fbf0dc559f6d4d3c9efc6e8af4ed0bf21d10c6)

fix(typo):fix bugs in onboarding. 

---

src/components/projects/serviceMgr/service.vue
src/components/projects/test/common/function/function.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/test/function/functionSummary.vue
src/components/projects/test/function/functionTaskDetail.vue
src/components/projects/test/report/testCase.vue
src/components/projects/workflow/status/container/productWorkflowStatus.vue
src/router/index.js

fix(typo):fix typo in test.

---

src/assets/css/component/dockerfile-template.less
src/assets/css/component/file-tree.less
src/assets/css/component/k8s-template.less
src/components/templateLibrary/chart/index.vue
src/components/templateLibrary/dockerfile/index.vue
src/components/templateLibrary/k8s/index.vue

fix: template style

---

src/components/delivery/version/index.vue

fix: fix hook configure style

---

src/components/projects/env/env_detail/components/updateK8sVarDialog.vue

feat: support search when updating environment variables

feat: support search when updating environment variables

---

src/components/projects/serviceMgr/helm/components/helm/help.vue
src/components/setting/config/mail.vue

fix(typo): fix document link

---

src/components/projects/detail_ope/create.vue
src/components/projects/rbac/addRoleBinding.vue

- [feat:searching for users using remote method.](https://github.com/koderover/zadig-portal/commit/9f446e74c74d6319efac03d80453a31c6497c2c0)
- [fix:remove filtering and use api results.](https://github.com/koderover/zadig-portal/commit/2d9eb513dc3aee37375fe28fb87dd7461a0e62be)
- project creation
- rbac configuration

feat:searching for users using remote method. 

---

src/components/projects/env/env_detail/components/pmLogDialog.vue
src/components/projects/env/serviceDetail/containerLog.vue

temporarily not showing kodespace doc link.

fix:temporarily not showing kodespace doc link.

---

src/components/projects/workflow/productTaskDetail.vue

fix: display the variable that has been set

fix: display the variable that has been set

---

src/components/projects/workflow/productTaskDetail/deploy.vue

fix:fix service name in helm deploy.

fix:fix service name in helm deploy.

---

src/components/projects/serviceMgr/helm/code.vue

cherry pick https://github.com/koderover/zadig-portal/pull/611

cherry-pick 611

---

src/components/projects/serviceMgr/helm/code.vue

fix: request data immediately after saving the build

fix: request data immediately after saving the build

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue

feat: support component and image name are inconsistent

feat: support component and image name are inconsistent

---

src/components/delivery/version/index.vue

fix doc link in project's version.Problem Summary:

fix(doc):fix doc link in project's version.

---

publish.sh

update build script to support buildx

chore:update build script to support buildx

---

src/api/index.js

move params from path to query.

feat:move params from path to query.

---

src/components/delivery/version/index.vue

feat: show hook when version list is empty.

feat:show hook when version list is empty.

---

src/components/projects/env/inner_env/serviceDetail.vue

feat:remove service scaling restrictions.

feat:remove service scaling restrictions.

---

src/components/setting/cluster/manage.vue

What's Changed: Update bad document link

fix(typo): fix bad doc link

---

src/components/insight/common/subTopbar.vue

feat:use project aliases as filter conditions.

feat:use project aliases as filter conditions.

---

src/components/projects/workflow/productTaskDetail/filterStatus.vue

fix:fix service name in task filter.

---

src/components/projects/workflow/productTaskDetail/deploy.vue
src/components/projects/workflow/productTaskDetail/filterStatus.vue

fix servicename in page.
cherry pick from:
- #625
- #613

fix:fix servicename in page.

---

src/components/projects/env/env_detail/components/manageServicesDialog.vue
src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue

fix: partial services

---

src/components/projects/serviceMgr/pm/updateEnv.vue
src/components/projects/serviceMgr/serviceK8s.vue

fix: parameter error

---

src/components/projects/serviceMgr/pm/updateEnv.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/628

cherry-pick 628

---

src/components/projects/serviceMgr/pm/updateEnv.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/628

cherry pick 628

---

src/components/projects/serviceMgr/pm/updateEnv.vue
src/components/projects/serviceMgr/serviceK8s.vue

Reverts koderover/zadig-portal#630

Revert "cherry pick 628"

---

src/components/projects/common/pm/pmConfig.vue

Add deploy variables to pm config.

feat:add deploy variables to pm config.

---

src/components/projects/env/env_detail/envDetailComp.vue

fix: cant update helm environment

fix: can't update helm environment

---

src/components/projects/env/env_detail/envDetailComp.vue

https://github.com/koderover/zadig-portal/pull/635

cherry-pick 635

---

src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/templateLibrary/chart/importChart.vue

- feat: load data once before updating gerrit

feat: load data once before updating gerrit

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/extension.vue

show payload in extension stage.

feat:show payload in extension stage.

---

src/components/setting/cluster/manage.vue

support cache directory configuration.

feat:support cache directory configuration.

---

src/components/projects/workflow/list/virtualListItem.vue

fix workflow's trigger shortcut.
How it Works:

fix:fix workflow's trigger shortcut.

---

src/components/common/workflowBuildRows.vue
src/components/common/workflowTestRows.vue
src/components/projects/env/env_detail/runWorkflow.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

enable tag selection when running workflows

feat: enable tag selection when running workflows

---

src/components/projects/env/env_detail/components/manageServicesDialog.vue

fix: switch the called interface to get all services

fix: switch the called interface to get all services

---

src/components/delivery/artifacts/detail.vue
src/components/delivery/artifacts/index.vue
src/components/projects/workflow/productTaskDetail/artifactDeploy.vue

fix:formatting service name.

---

src/components/entry/home/sidebar.vue

add tooltip to sidebar when it's closed.
How it Works:

feat:add tooltip to sidebar when it's closed.

---

src/components/setting/cluster/manage.vue

fix typo and set subpath to default value.

fix:fix typo and set subpath to default value.

---

src/components/common/workflowBuildRows.vue

feat:support search during branch selection.
How it Works:

feat:support search during branch selection.

---

src/components/projects/rbac/addRoleBinding.vue

fix projectName missing in API.

fix:fix projectName missing in API.

---

src/components/projects/workflow/common/k8sArtifactDeploy.vue

fix:fix searching image in artifact deploy.

fix:fix searching image in artifact deploy.

---

src/components/projects/workflow/common/k8sArtifactDeploy.vue

fix observe data bug in imgs.
How it Works:

fix:fix observe data bug in imgs.

---

src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue

Hit for creating env in vm project is wrong

fix(typo): fix wrong hit when create env for vm project

---

src/components/projects/build/envVariable.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue

- registry of the current environment is selected by default
- remove the validation of the environment variable' value

fix: optimized fixes

---

src/components/setting/helm/manage.vue

Modify the verification of the url to the protocol

feat: modify the verification of the url to the protocol

---

src/api/index.js
src/components/projects/policy/home.vue

delete btn arise some auth problems
not restful api can't get some params
How it Works:
1.remove delele btns in private auth scene
2.fix api can't get params

fix: remove delele btns in private auth scene and fix api can't get params 

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/workflow/common/runWorkflow.vue

feat: host environments can use registry

feat: host environments can use registry

---

src/components/projects/guide/pm/delivery.vue
src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue
src/components/projects/workflow/workflowEditor/productWorkflow/sidebar.vue
src/components/projects/workflow/workflowEditor/productWorkflow/tab.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
src/mobile/pipelines/detail.vue
src/utilities/wordTranslate.js

change distribute stage to distribute deploy.

feat:change distribute stage to distribute deploy.

---

src/components/projects/build/commonBuild.vue
src/components/projects/build/configDetail.vue
src/components/projects/serviceMgr/serviceK8s.vue

fixed: 
- cant edit build name
- optimize loading and style
- show the added steps

fix: about the build

---

src/api/index.js
src/components/projects/env/env_detail/components/manageServicesDialog.vue
src/components/projects/serviceMgr/serviceK8s.vue

force environment update when adding services

fix:force environment update when adding services

---

src/components/projects/serviceMgr/helm/code.vue

- fix: modify build padding bottom

fix: modify build padding bottom

---

src/assets/css/component/service-detail.less
src/components/projects/common/pm/addHost.vue
src/components/projects/common/pm/pmConfig.vue
src/components/projects/env/env_detail/common/pmXtermDebug.vue
src/components/projects/env/inner_env/pmServiceDetail.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/setting/host/importHosts.vue
src/components/setting/host/manage.vue

- host debug
- host add status

feat: host service support ssh.

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/serviceMgr/serviceHost.vue
src/components/projects/serviceMgr/servicePm.vue

fix: open tar package rules

---

package.json
src/components/projects/common/pm/addHost.vue
yarn.lock

feat: validate ip

---

src/components/projects/common/pm/addHost.vue

fix: trim only the ip string

---

src/components/projects/common/pm/addHost.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/667

cherry pick 667

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/extension.vue

supports response info display in extension stage.

feat:supports response info display in extension stage.

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/extension.vue

fix:show headers in extension request.

---

src/api/index.js

fix response's data desc undefined

fix: fix response's data desc undefined.

---

src/components/projects/serviceMgr/helm/components/helm/matchRule.vue

Helm project custom service component parsing logic addition failed

fix: Helm project custom service component parsing logic addition failed

---

src/components/common/artifactDownload.vue

modify test results download API

feat:modify test results download API.

---

src/common/repoSelect.vue
src/components/projects/test/common/function/container/taskDetailTest.vue
src/components/projects/workflow/common/repoJump.vue
src/components/setting/integration/code.vue

feat:supports gitee in providers.

---

src/components/common/artifactDownload.vue

change style of file table.
set  static  height to '300px'

fix(style):change style of file table.

---

src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue

fix route query redirect in service.

fix:fix route query redirect in service.

---

config/index.js
src/components/common/workflowBuildRows.vue
src/components/projects/build/envVariable.vue
src/components/projects/build/jenkinsBuild.vue
src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue

enhance jenkins build params
How it Works:

feat: enhance jenkins build params

---

src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/env/createHelmEnv.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

preserve git info when importing yaml.

feat:preserve git info when importing yaml.

---

src/api/index.js
src/assets/css/component/env-detail.less
src/components/projects/env/createHelmEnv.vue
src/components/projects/env/env_detail/components/shareEnvDialog.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue

support the creation of shared environments

feat:support the creation of shared environments

---

src/components/projects/common/importValues/repository.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue

fix minor bugs in helm service.

fix:fix minor bugs in helm service.

---

src/components/projects/env/env_detail/components/shareEnvDialog.vue

fix:add command to istio installtion.

fix:add command to istio installtion.

---

src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue

fix:add autoSync prop to component.

fix:add autoSync prop to component.

---

src/components/projects/env/env_detail/components/shareEnvDialog.vue

fix:don't show command when istio is installed.

fix:don't show command when istio is installed.

---

src/components/projects/common/importValues/repository.vue
src/components/projects/env/env_detail/envDetailComp.vue

Add space to typo and clean code.

fix:add space to typo and clean code.

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/projects/serviceMgr/k8s/container/policy.vue

fix:jenkins build

---

src/components/projects/env/env_detail/envDetailComp.vue

fix:add doc link to ref.

---

src/components/projects/common/importValues/repository.vue
src/components/projects/env/env_detail/envConfig/commonConfig.vue

feat: hide the associated services in the helm env config

feat: hide the associated services in the helm env config

---

src/components/common/workflowBuildRows.vue
src/components/projects/workflow/productTaskDetail.vue

fix:fix serviceName in jenkins build.

fix:fix serviceName in jenkins build.

---

src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

fix:fix autoSync undefined.

---

src/components/setting/integration/account.vue

Set scope to required and remove autocompletion in Oauth

fix:set scope to required and remove autocompletion

---

src/components/projects/build/envVariable.vue

fix: env validate error

---

src/components/projects/env/env_detail/components/shareEnvDialog.vue

fix:checking status after disable share env.

---

src/api/index.js
src/common/xtermDebug.vue
src/components/projects/env/inner_env/serviceDetail.vue

changing environment related API route.

feat:changing environment related API route.

---

src/api/index.js
src/components/delivery/version/helm/createVersion.vue
src/components/delivery/version/helm/createVersion/push.vue

supports retag image in helm version.

feat:supports retag image in helm version.

---

src/components/delivery/version/helm/createVersion/push.vue
src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue

fix: AWS registry hasn't namespace

fix: AWS registry hasn't namespace

---

src/api/index.js
src/components/setting/config/cache.vue

feat: timing clean cache

---

src/components/projects/detail_ope/components/cusDeliverable.vue

fix: default value for image name rules

fix: default value for image name rules

---

src/api/index.js
src/components/projects/env/env_detail/envConfig/commonConfig.vue

feat: modify the interface parameters for the environment configuration

feat: modify the interface parameters for the environment configuration

---

src/api/index.js
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/store/modules/serviceManage.js

feat:release name support renaming.

---

src/components/projects/env/inner_env/pmServiceDetail.vue

show host name and label in service detail.

feat:show host name and label in service detail.

---

src/api/index.js
src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
src/components/projects/env/env_detail/envDetailComp.vue

fix: update updatable services

fix: update updatable services

---

src/api/index.js
src/common/repoSelect.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/projects/test/common/function/functionDetail.vue

feat: add a group api key

---

src/components/setting/config/cache.vue

fix: close request

---

src/api/index.js
src/common/repoSelect.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/projects/test/common/function/functionDetail.vue

fix: cherry-pick pr:720->Release 1.11.0

fix: cherry-pick pr:719->Release 1.11.0

---

src/components/setting/config/cache.vue

cherry-pick: pr:1312->Release 1.11.0

fix: cherry-pick pr:720->Release 1.11.0

---

src/components/entry/home.vue
src/components/projects/detail_ope/home.vue
src/components/setting/integration/code.vue
src/main.js

fix: project error

---

src/components/entry/home.vue
src/components/projects/detail_ope/home.vue
src/components/setting/integration/code.vue
src/main.js

fix: cherry-pick724->release1.11 

---

src/components/setting/integration/code.vue

fix: codehub v-if error

---

src/components/setting/integration/code.vue

fix: cherry-pick 725->release1.11

---

src/components/entry/home.vue

fix: publicKey

---

src/components/entry/home.vue

fix: cherry-pick 727 to release1.11

---

src/components/projects/serviceMgr/helm/components/helm/aside.vue

add confirm dialog when saving release name.

feat:add confirm dialog when saving release name.

---

src/components/setting/registry/manage.vue

fix: confirm popup

---

src/components/setting/registry/manage.vue

fix: cherry-pick 729 to release1.11

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/manage.vue

fix: cherry-pick 733 to release 1.11

---

src/components/entry/home.vue

fix:get public key in created hook.

fix:get public key in created hook.

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/manage.vue

Reverts koderover/zadig-portal#733

Revert "fix: remove window btoa privatekey"

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/manage.vue

Reverts koderover/zadig-portal#734

Revert "fix: cherry-pick 733 to release 1.11"

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/740

cherry-pick 740

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/manage.vue
src/components/setting/integration/code.vue

fix: cherry-pick 739 to release1.11

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/manage.vue
src/components/setting/integration/code.vue

fix: window.atob

---

src/assets/css/component/service-editor.less
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/serviceMgr/serviceK8s.vue

show `addToEnvBtn` when service is added.

fix:show addToEnvBtn when service is added.

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/setting/integration/code.vue
src/components/setting/registry/manage.vue

fix: jenkins bug and tip and popup

fix: jenkins bug and tip and popup

---

src/components/projects/detail_ope/components/cusDeliverable.vue
src/components/setting/integration/code.vue
src/components/setting/registry/manage.vue

fix: jenkins bug and tip and popup

fix: cherry-pick 745 to release1.11.0

---

src/components/projects/build/commonBuild.vue
src/components/projects/common/hosting/serviceBuild.vue

fix: host build saves multiple times in a row throws an error

fix: host build saves multiple times in a row throws an error

---

src/components/projects/build/commonBuild.vue
src/components/projects/common/hosting/serviceBuild.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/743

cherry pick 743

---

src/components/projects/detail_ope/components/cusDeliverable.vue

fix: service jenkins not show

---

src/components/projects/detail_ope/components/cusDeliverable.vue

fix: cherry-pick 749 to release1.11.0

---

src/components/projects/serviceMgr/serviceK8s.vue

fix:fix var undefined.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/753

cherry-pick 753

---

src/components/projects/env/env_detail/envDetailComp.vue

change payload in pm env when updating.

fix:change payload in pm env when updating.

---

src/components/common/workflowBuildRows.vue

fix: can select pr when run workflow

fix: can select pr when run workflow

---

src/components/common/workflowBuildRows.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/759

cherry-pick 759

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue

fix redirect when adding service.

fix:fix redirect when adding service.

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue

fix redirect when adding service.

cherry-pick:763

---

src/components/projects/env/env_detail/envDetailComp.vue

Reverts koderover/zadig-portal#756

Revert "fix:change payload in pm env when updating."

---

src/components/projects/env/env_detail/envDetailComp.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/767

cherry pick 767

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue

fix error msg in distribteDeploy.

fix:fix error msg in distribteDeploy.

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue

Cherry pick for :#https://github.com/koderover/zadig-portal/pull/

cherry-pick:#770

---

src/components/projects/serviceMgr/common/importFromTemplate.vue

Render variables when preview k8s yaml.

fix:render variables when preview k8s yaml.

---

src/components/projects/serviceMgr/common/importFromTemplate.vue

cherry pick for:
https://github.com/koderover/zadig-portal/pull/772

cherry pick:#772

---

src/components/profile/common/config.js
src/components/setting/integration/account.vue

https://github.com/koderover/zadig-portal/pull/774

cherry-pick:#744

---

src/components/profile/common/config.js
src/components/setting/integration/account.vue

add doc link to custom account.

feat:add doc link to custom account.

---

src/api/index.js
src/components/setting/integration/components/sonarOperate.vue
src/components/setting/integration/home.vue
src/components/setting/integration/sonar.vue

feat: sonar

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/serviceMgr/serviceK8s.vue

support update service when import from template.
How it Works:

feat:support update service when import from template.

---

src/components/projects/env/env_detail/components/updateK8sVarDialog.vue

fix:disable btn when vars is empty.

fix:disable btn when vars is empty.

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry pick 
https://github.com/koderover/zadig-portal/pull/777
How it Works:

cherry pick#777

---

src/components/projects/env/env_detail/components/updateK8sVarDialog.vue

cherry pick https://github.com/koderover/zadig-portal/pull/779
How it Works:

cherry-pick #779

---

config/index.js
src/api/index.js
src/components/projects/rbac/addRole.vue
src/components/setting/users/components/roleOperate.vue
src/components/setting/users/editUserInfo.vue
src/components/setting/users/home.vue
src/components/setting/users/manage.vue
src/components/setting/users/role.vue
src/router/index.js

feat: system role

---

src/components/setting/users/home.vue
src/components/setting/users/role.vue

fix: admin edit disabled

---

src/components/projects/test/common/function/functionDetail.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

fix:  webhook defalut empty array

fix: defalut empty array

---

src/components/setting/integration/code.vue

update the hits for Gitee integration

fix typo: fix typo for Gitee integration

---

src/api/index.js
src/components/setting/integration/account.vue

feat: default  login account 

---

src/components/projects/test/common/function/container/advancedConfig.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

fix: push to unshift

---

src/api/index.js
src/assets/css/component/build-template.less
src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/projects/build/commonBuild.vue
src/components/projects/build/config.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/detail_ope/home.vue
src/components/templateLibrary/builds/advancedConfig.vue
src/components/templateLibrary/builds/buildEnv.vue
src/components/templateLibrary/builds/envVariable.vue
src/components/templateLibrary/builds/fileAside.vue
src/components/templateLibrary/builds/fileEditor.vue
src/components/templateLibrary/builds/fileTree.vue
src/components/templateLibrary/builds/index.vue
src/components/templateLibrary/builds/otherSteps.vue
src/components/templateLibrary/builds/zadigBuild.vue
src/components/templateLibrary/common/subTopbar.vue
src/router/index.js

add build configuration template library.

feat:add build configuration template library.

---

src/components/setting/integration/account.vue

fix: params

---

src/components/projects/build/commonBuild.vue
src/components/projects/build/configDetail.vue
src/components/projects/build/envVariable.vue
src/components/templateLibrary/builds/envVariable.vue

- [fix:fix build env typo](https://github.com/koderover/zadig-portal/commit/57279b3944d822c89db14fe3cbfe5aff78aa72cd)
- [feat:saving config to template.](https://github.com/koderover/zadig-portal/commit/7fcd322ff017abdc4640bfebb8989c901d3eea98)

fix: fix build template bugs.

---

src/components/setting/integration/account.vue
src/components/setting/users/editUserInfo.vue
src/components/setting/users/manage.vue
src/components/setting/users/role.vue

fix role refresh and modify account tip

fix role refresh and modify account tip 

---

src/components/projects/build/configDetail.vue

fix:fix var is undefined in computed.

fix:fix var is undefined in computed

---

src/components/setting/integration/account.vue

fix: el-button to el-tag filter github

fix: el-button to el-tag filter github

---

src/api/index.js
src/components/projects/build/commonBuild.vue
src/components/projects/build/jenkinsBuild.vue
src/components/setting/integration/jenkins.vue

feat: suport multi jenkins

---

src/components/entry/home/topbar.vue
src/components/templateLibrary/builds/otherSteps.vue

fix z-index in preview drawer.
How it Works:

fix:fix z-index in preview drawer.

---

src/components/projects/build/envVariable.vue
src/components/templateLibrary/builds/envVariable.vue

fix(typo):fix typo of vars.

---

src/components/projects/env/createEnv.vue
src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue

feat:enable share env in helm.

---

src/components/projects/build/envVariable.vue
src/components/templateLibrary/builds/envVariable.vue

fix:fix typo of var.

---

src/common/serviceRepoSelect.vue

fix(style):fix style of serviceRepoSelect comp.
How it Works:

fix(style):fix style of serviceRepoSelect comp.

---

src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue

fix:fix envList when adding service to helm.
How it Works:

fix:fix envList when adding service to helm.

---

src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue

fix:fix typo

---

src/api/index.js

- method: GET
endpoint: "/api/aslan/stat/dashboard/overview" -> "/api/v1/picket/stat/dashboard/overview"
- method: GET
endpoint: "/api/aslan/stat/dashboard/test"-> "/api/v1/picket/stat/dashboard/test"
- method: GET
endpoint: "api/aslan/stat/dashboard/deploy"-> "api/v1/picket/stat/dashboard/deploy"
- method: GET
endpoint: "/api/aslan/stat/dashboard/build"-> "/api/v1/picket/stat/dashboard/build"

fix(API):fix API route.

---

src/components/projects/build/commonBuild.vue

fix:add repo info when creating new target_repo.
How it Works:

fix:add repo info when creating new target_repo.

---

src/components/projects/serviceMgr/k8s/serviceEditor.vue

fix: error of the newly created service after saving

fix: error of the newly created service after saving

---

src/api/index.js
src/components/projects/build/commonBuild.vue
src/components/projects/build/config.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/hosting/serviceModules.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/buildDeploy.vue

- a service can has multiple builds in k8s/helm/host project 
- workflow can select build

feat: multiple build names

---

src/components/projects/build/commonBuild.vue

fix:set select to disable when jenkins is't available.

fix:set select to disable when jenkins is't available. 

---

src/components/projects/build/commonBuild.vue

cherry pick: cherry pick for  #813 #814

---

src/components/projects/build/commonBuild.vue

cherry pick: cherry pick for #813 #814

cherry pick: cherry pick for #813 #814

---

src/api/index.js
src/components/projects/env/inner_env/pmServiceDetail.vue
src/components/projects/rbac/addRole.vue

feat: add permission for host login

feat: add permission for host login

---

src/components/setting/helm/manage.vue

fix typo: fix typo in placeholder

---

src/components/setting/helm/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/823

cherry pick: #823 fix typo in placeholder

---

src/components/projects/serviceMgr/k8s/container/policy.vue

feat: service auto deploy

---

src/api/index.js
src/common/variableEditor.vue
src/common/variablePreviewEditor.vue
src/components/projects/env/env_detail/components/manageK8sServicesDialog.vue
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/serviceK8s.vue

feat:optimize variable editor.

---

src/api/index.js
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/templateLibrary/chart/aside/variableList.vue
src/components/templateLibrary/chart/index.vue

fix: button position and tootip and api

fix: button position and tootip and api

---

src/components/setting/integration/code.vue

feat: remove codehub

---

src/common/variablePreviewEditor.vue

fix:fix error style in editor.

fix:fix error style in editor.

---

src/common/variablePreviewEditor.vue

fix:fix errors undefined.

---

src/api/index.js
src/assets/css/common/common.less
src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/workflow/productTaskDetail/filterStatus.vue

feat: helm environment can select chart names

feat: helm environment can select chart names

---

src/components/projects/env/k8sPmEnv/createK8sEnv.vue

fix: create rollbackable k8s environments

fix: create rollbackable k8s environments

---

src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/envDetailComp.vue

chore: modify desc and delete useless code

chore: modify desc and delete useless code

---

src/components/projects/scanner/create.vue

fix: modify the parameters of the request image list

fix: modify the parameters of the request image list

---

src/components/projects/env/k8sPmEnv/varList.vue

Add variable editor to k8s env creation.
How it Works:

feat:add variable editor to k8s env creation.

---

src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue

[feat:add variable preview editor to env creation](https://github.com/koderover/zadig-portal/commit/6ff792d5d77ace06e1042dcbd45909fe61be68b1)
How it Works:

fix:add variable preview editor to env creation 

---

src/components/projects/workflow/productTaskDetail.vue

fix:get release info from task detail.

fix:get release info from task detail.

---

src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

fix:set default value when source_detail undefined.

fix:set default value when source_detail undefined.

---

src/api/index.js
src/components/projects/build/otherSteps.vue
src/components/projects/build/zadigBuild.vue
src/components/templateLibrary/builds/otherSteps.vue

fix(permission):add query 'projectName' to API.

fix(permission):add query 'projectName' to API. 

---

src/api/index.js
src/components/projects/build/otherSteps.vue
src/components/projects/build/zadigBuild.vue
src/components/templateLibrary/builds/otherSteps.vue

cherry-pick:#841

---

src/api/index.js
src/components/projects/scanner/create.vue

cherry-pick:#849

---

src/api/index.js
src/components/projects/scanner/create.vue

fix(permission):add query 'projectName' to API.

fix(permission):add query 'projectName' to API.

---

src/api/index.js

fix: project name params

---

src/components/common/workflowBuildRows.vue
src/components/projects/env/env_detail/runWorkflow.vue
src/components/projects/scanner/common/runScannerTask.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue

feat: create items in select boxes

feat: create items in select boxes

---

src/components/projects/scanner/create.vue

feat: hide jumps for add scan environments

feat: hide jumps for new scan environments

---

src/components/projects/env/env_detail/components/chartList.vue

feat: display helm release by default

feat: display helm release by default

---

src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

cherry-pick:fix source_detail undefined.#845

cherry-pick:fix source_detail undefined.#845 

---

src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

fix:fix source_detail undefined.
How it Works:

fix:fix source_detail undefined.

---

src/api/index.js
src/components/delivery/common/subTopbar.vue
src/components/delivery/version/index.vue
src/components/entry/home.vue
src/components/entry/home/sidebar.vue
src/components/entry/home/subTopbar.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/hosting/serviceModules.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/editor/folder.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/setting/users/manage.vue
src/directive/permission/hasPermi.js
src/main.js
src/mixin/permissionMixin.js
src/store/index.js
src/store/modules/globalPermission.js
src/store/modules/projectPermission.js
src/store/mutations.js
src/utilities/checkPermission.js

feat:permission enhancement.

---

src/components/projects/scanner/common/advancedConfig.vue

fix:fix variable name.

---

src/components/projects/scanner/common/advancedConfig.vue

fix:fix variable name in comment.

fix:fix variable name in comment.

---

src/components/projects/scanner/common/advancedConfig.vue

fix: code scan edit status is wrong

fix: code scan edit status is wrong

---

src/api/index.js
src/components/common/gitFileTree.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitFileTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/templateLibrary/chart/importChart.vue

feat: repos support  to import from gitee

---

src/components/projects/common/pm/addHost.vue
src/components/setting/host/importHosts.vue
src/components/setting/host/manage.vue

feat: enhanced cloud host detection

feat: enhanced cloud host detection

---

src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/env/env_detail/envDetailComp.vue

- refresh service list
- environment variables filter by service name

feat: optimize environments

---

src/components/projects/scanner/common/runScannerTask.vue

fix:fix tag undefined when run scanner task.

fix:fix tag undefined when run scanner task.

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/setting/integration/code.vue

feat: alias

---

src/components/projects/common/importValues/repository.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/setting/integration/code.vue

fix: add alias
