koderover/zadig-portal

src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/productDetail.vue

fix:change tooltip of run btn.

---

src/components/entry/home/subTopbar.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/serviceMgr/servicePm.vue

fix:fix permission of prod env.

fix:fix permission of prod env.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

fix: build error

---

src/components/projects/env/env_detail/envDetailComp.vue

fix:fix permission in create env btn.

fix:fix permission in create env btn.

---

src/components/projects/build/configDetail.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/directive/permission/hasPermi.js

fix:fix permission bugs.

---

src/components/projects/guide/pm/config.vue

fix: delete highlight class

---

src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/env/k8sPmEnv/varList.vue
src/components/projects/env/pmEnv/createPmEnv.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/artifactDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/buildDeploy.vue

UI: optimize user experience 

---

src/api/index.js
src/components/projects/detail_ope/components/deleteProduct.vue
src/components/projects/detail_ope/components/deleteProject.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/detail_ope/home.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/serviceMgr/common/importFromNamespace.vue
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/store/modules/projectList.js

feat: import service from k8s namespace

feat: import service from k8s namespace

---

src/api/index.js
src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/common/gitFileTree.vue
src/components/common/testTrigger.vue
src/components/common/workflowBuildRows.vue
src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/common/importValues/treeFile.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
src/components/projects/env/env_detail/runWorkflow.vue
src/components/projects/scanner/common/runScannerTask.vue
src/components/projects/scanner/create.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitFileTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo/importValues.vue
src/components/projects/workflow/common/runCommonWorkflow.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
src/components/templateLibrary/chart/importChart.vue
src/components/templateLibrary/chart/index.vue
src/mobile/pipelines/runWorkflow.vue

feat: git enhancement

---

src/components/projects/serviceMgr/helm/components/editor/codeMirror.vue

feat: the editor in the helm service is searchable

feat: the editor in the helm service is searchable

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/extension.vue

Problem Summary: the link of workflow extension description is wrong
What's Changed: revise the link

fix typo: fix document link

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

feat: webhook add help link

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/setting/integration/code.vue

feat: support standard git enhancement

feat: support standard git enhancement

---

src/components/projects/serviceMgr/common/importFromNamespace.vue
src/components/projects/serviceMgr/common/serviceTree.vue

fix: adjust the layout and make the update button available

fix: adjust the layout and make the update button available

---

src/api/index.js
src/components/projects/build/otherSteps.vue
src/components/projects/common/importConfig/index.vue
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/components/projects/workflow/common/pmArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue

fix:add projectName to API query.

fix:add projectName to API query.

---

src/components/projects/common/taskList.vue
src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/workflow/commonDetail.vue
src/components/projects/workflow/commonTaskDetail.vue
src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/productTaskDetail.vue
src/directive/permission/hasPermi.js
src/main.js
src/utilities/checkPermission.js

fix permission in collaborative mode.

fix:fix permission in collaborative mode.

---

src/components/setting/config/cache.vue
src/components/setting/config/link.vue
src/components/setting/config/proxy.vue
src/components/setting/config/quota.vue

Problem Summary: the help link can be more accurate
What's Changed: update links
How it Works: makes link more accurate

fix typo: makes link more accurate

---

src/directive/permission/hasPermi.js
src/store/modules/globalPermission.js
src/store/modules/projectPermission.js
src/utilities/checkPermission.js

fix:fix permission checking bug.

fix:fix permission checking bug. 

---

src/common/repoSelect.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/serviceK8s.vue

fix: repo_namespace and build params

fix: repo_namespace

---

src/common/serviceRepoSelect.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue

fix: notify and validate

---

src/components/projects/guide/k8s/service.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/editor/order.vue

fix: optimize experience

---

src/components/projects/guide/k8s/service.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/editor/order.vue

cherry pick https://github.com/koderover/zadig-portal/pull/897

cherry pick 897

---

src/components/templateLibrary/builds/envVariable.vue

the description of `REPONAME_index`/`REPO_index` is hard to understand
What's Changed: update the description for `REPONAME_index`/`REPO_index`

fix typo: update the description of REPONAME_index/REPO_index for better understanding

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

fix: namespace

---

src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/serviceMgr/common/serviceTree.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/902

cherry pick 902

---

src/api/index.js
src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue

fix:fix error response when delete service.

fix:fix error response when delete service.

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/components/templateLibrary/chart/aside/variableList.vue
src/components/templateLibrary/k8s/fileEditor.vue

`批量更新` is hard to understand
What's Changed: update typo

fix typo: update typo for service template

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/projects/build/commonBuild.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/importValues/index.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

fix: bug and ui

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/projects/build/commonBuild.vue
src/components/projects/common/hosting/serviceBuild.vue
src/components/projects/common/importValues/index.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

cherry-pick 907

---

src/components/projects/build/configDetail.vue

fix:fix permission actions.
How it Works:

fix:fix permission actions.

---

src/api/index.js

fix: update the default value of is_delete to true

fix: update the default value of is_delete to true

---

src/api/index.js

cherry-pick https://github.com/koderover/zadig-portal/pull/911

cherry-pick 911

---

src/components/projects/test/common/function/container/testRow.vue

fix:fix permission in test row.

---

src/components/projects/test/common/function/container/testRow.vue

cherry pick:#913

---

src/common/serviceRepoSelect.vue
src/components/projects/build/commonBuild.vue
src/components/projects/build/zadigBuild.vue
src/directive/permission/hasPermi.js

feat: build templates support variable settings
patch 1.12.0

feat: build templates support variable settings

---

src/common/serviceRepoSelect.vue
src/components/projects/build/commonBuild.vue
src/components/projects/build/zadigBuild.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/894
feat: build templates support variable settings

cherry pick 894

---

src/components/projects/build/otherSteps.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue
src/components/templateLibrary/builds/fileEditor.vue
src/utilities/checkPermission.js

[chore:clean console.log](https://github.com/koderover/zadig-portal/commit/c3b38e2a4467e9728e66ae3f3c54908dcb3de847)
How it Works:

chore:clean console.log 

---

src/components/entry/home/subTopbar.vue

chore:change variable name in template.
change `this.projectName` to `projectName`

chore:change variable name in template.

---

src/components/projects/scanner/create.vue

fix:fix advanced config not work in scanner.
How it Works:

fix:fix advanced config not work in scanner.

---

src/api/index.js
src/common/serviceRepoSelect.vue
src/components/projects/scanner/taskDetail.vue

feat:  cancel scanner

---

src/common/serviceRepoSelect.vue
src/components/projects/build/zadigBuild.vue

fix: build bug

---

src/components/projects/build/commonBuild.vue
src/components/projects/build/zadigBuild.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/926

cherry pick 926

---

src/api/index.js
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/components/setting/cluster/manage.vue

feat: enhanced multi-cluster upgrade capability

feat: enhanced multi-cluster upgrade capability

---

src/api/index.js
src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/918

cherry-pick 918

---

src/components/projects/build/configDetail.vue
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue

- build jump pages to display service information
- remove the operation of updating environment variables

feat: optimize the experience

---

src/components/projects/build/configDetail.vue
src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/931

cherry-pick 931

---

config/index.js
src/components/projects/guide/helm/runtime.vue

fix: valuesData

---

src/components/setting/cluster/manage.vue

feat: hide Dind

---

src/components/setting/cluster/manage.vue

make link more accurate
What's Changed: update link

fix typo: make link more accurate

---

src/components/setting/cluster/manage.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/940

cherry-pick 940

---

src/components/setting/cluster/manage.vue

fix typo: fix wrong link

---

src/components/projects/env/inner_env/serviceDetail.vue

feat: add host name of service

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

cherry pick:#948

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

fix:fix the problem of adding new code repo.

fix:fix the problem of adding new code repo. 

---

src/common/repoSelect.vue

fix:fix soure is undefined when call addFirstRepo.

fix:fix soure is undefined when call addFirstRepo.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/basicInfo.vue

feat: hide revert btn in external scene

feat: hide revert btn in external scene

---

src/components/projects/common/pm/serviceList.vue
src/components/projects/guide/pm/config.vue

fix: build name error in host scene

fix: build name error in host scene

---

src/components/common/workflowBuildRows.vue

fix: timer name undefined

---

src/components/projects/env/inner_env/serviceDetail.vue

fix:fix permission action.
How it Works:

fix:fix permission action.

---

src/components/projects/serviceMgr/helm/code.vue

feat: expand the scope of the helm service editor

feat: expand the scope of the helm service editor

---

src/components/delivery/version/helm/createVersion.vue
src/components/delivery/version/helm/createVersion/push.vue

feat: image is optional when creating helm version

feat: image is optional when creating helm version

---

src/components/projects/serviceMgr/servicePm.vue

fix: build error in host scene

fix: build error in host scene

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

fix: build template error

---

src/api/index.js
src/common/xtermDebug.vue
src/components/projects/env/inner_env/serviceDetail.vue

supports debug container alpha.

feat:supports debug container alpha.

---

src/router/index.js

fix(typo):change typo of chunk name.

fix(typo):change typo of chunk name.

---

src/api/index.js
src/components/entry/home/common/notification.vue

- [fix(style):fix style of notification.](https://github.com/koderover/zadig-portal/commit/b3f7ddb071af6788a09c0da4f4feab78a52c1977)

fix(style):fix style of notification.

---

src/api/index.js

fix: service update interface changed from post to put

---

src/components/projects/env/inner_env/pmServiceDetail.vue

fix: host bug in env

---

src/components/projects/env/env_detail/envDetailComp.vue

feat: refresh the chart list

---

src/components/projects/common/pm/pmConfig.vue

fix: host bug in service

---

src/components/projects/env/pmEnv/createPmEnv.vue

fix: hostids in create env scene

---

src/components/projects/env/env_detail/components/pmHostItem.vue

fix: checkAll

---

src/components/projects/common/hosting/addHostEnv.vue

fix: don't verify associated mirror repositories

fix: don't verify associated mirror repositories

---

src/api/index.js
src/components/projects/serviceMgr/k8s/serviceEditor.vue

fix:add query to API when status is added.

fix:add query to API when status is added.

---

build/webpack.base.conf.js
build/webpack.prod.conf.js

fix: use dll plugin in webpack.prod.conf.

---

src/components/projects/common/taskList.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail/deploy.vue
src/utilities/utilities.js

fix:fix the service name format.

fix:fix the service name format. 

---

src/components/projects/common/taskList.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail/deploy.vue
src/utilities/utilities.js

fix:fix the service name format.

fix:fix the service name format.

---

src/components/projects/common/taskList.vue

fix:fix position of service_module.
`${item.service_module}(${item.service_name})`

fix:fix position of service_module.

---

src/components/projects/host/home.vue
src/components/setting/host/index.vue

fix: scroll in host

---

src/components/projects/host/home.vue
src/components/setting/host/index.vue

cherry-pick  990 to release-20220616

---

src/common/host/importHosts.vue

fix:fix host template.
How it Works:

fix:fix host template.

---

src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/productTaskDetail/filterStatus.vue

fix:remove split func in serviceName's filter.

fix:remove split func in serviceName's filter.

---

src/components/profile/manage.vue
src/mobile/profile.vue

fix:fix last login time. 

---

src/assets/css/component/service-detail.less
src/components/projects/env/inner_env/serviceDetail.vue

fix: distinguish the three red states of the service

fix: distinguish the three red states of the service

---

src/components/delivery/artifacts/detail.vue

remove split func in serviceName.

fix:remove split func in serviceName.

---

src/components/projects/common/pm/pmConfig.vue
src/components/projects/env/pmEnv/createPmEnv.vue

data structure has been changed due to API changes.
old:
```
allHost:  [optObj, ...]
```
new:
```
allHost:  [{ label: '', options: [optObj, ...]}]
```

fix: host data statistics error

---

src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue

fix: services list in update scene

fix: services list in update scene

---

src/api/index.js
src/components/setting/cluster/manage.vue

Dind supports configuring storage resources

feat: dind supports configuring storage resources

---

src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue

- `release_imageSubTask` is undefined when the release method is `object`.
-  fix release method removal not working in workflow's edit release page.

fix:fix release_imageSubTask undefined.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/basicInfo.vue

fix: deployType of undefined

---

src/components/projects/common/taskList.vue

feat:remove unused structure in API.
reference:https://github.com/koderover/zadig/pull/1714

feat:remove unused  data structure in API.

---

src/components/delivery/version/index.vue

feat: display status information in the version management of the helm project

feat: display status information in the version management of the helm project

---

src/api/index.js
src/components/projects/common/importConfig/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/env/env_detail/common/envConfig.vue
src/components/projects/env/env_detail/envConfig/commonConfig.vue
src/components/projects/env/env_detail/envConfig/home.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue

Environment configuration (including creating environment and environment configuration):
- save git info
- add automatic sync
- select files only (previously supported selecting directories)
Adjust the code structure of the imported repo: 
- filetype: remove string, use uniform array
- add namespace

feat: environment configuration saves git information

---

src/components/projects/common/importValues/repository.vue

Problem Summary:  tip info inaccurate
What's Changed: update tip info

fix typo: fix inaccurate tip info

---

src/components/projects/common/pm/pmConfig.vue
src/components/projects/env/inner_env/serviceDetail.vue
src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue
src/components/projects/workflow/status/container/customWorkflowStatus.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/utilities/wordTranslate.js

fix: fix multiple bugs.

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1015

cherry pick 1015

---

src/components/projects/detail_ope/detail.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

fix: ui and bugs

---

src/components/projects/env/inner_env/serviceDetail.vue
src/components/templateLibrary/builds/fileEditor.vue
src/components/templateLibrary/dockerfile/fileEditor.vue
src/directive/permission/hasPermi.js

fix the disabled bug of the permission button

fix: fix the disabled bug of the permission button

---

src/components/projects/env/inner_env/serviceDetail.vue
src/components/templateLibrary/builds/fileEditor.vue
src/components/templateLibrary/dockerfile/fileEditor.vue
src/directive/permission/hasPermi.js

cherry-pick https://github.com/koderover/zadig-portal/pull/1021

cherry pick 1021

---

src/api/index.js
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/commonDetail.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/productCustomDetail.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/status/container/customWorkflowStatus.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stage.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

feat: add auth

---

src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

feat: multi build

---

src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue

fix:try to fix the SSE log closing issue.

fix:try to fix the SSE log closing issue.

---

src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue

fix:try to fix the SSE log closing issue.

cherry-pick:#1026

---

src/api/index.js
src/components/entry/home.vue
src/main.js
src/utilities/encrypt.js

feat: upload the data of the number of users

feat: upload the data of the number of users

---

src/api/index.js
src/components/entry/home.vue
src/main.js
src/utilities/encrypt.js

cherry-pick https://github.com/koderover/zadig-portal/pull/1028

cherry pick 1028

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/utilities/wordTranslate.js

fix: status

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue

fix: failed to obtain repo information for template build

fix: failed to obtain repo information for template build

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1032

cherry pick 1032

---

src/components/projects/workflow/common/runCustomWorkflow.vue

fix: remove default service

---

src/common/xtermLog.vue
src/components/projects/workflow/list/productRow.vue
src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue

fix: log and name length

---

src/common/xtermLog.vue
src/components/projects/workflow/list/productRow.vue

fix: workflow name length

---

src/components/entry/home/subTopbar.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue
src/components/projects/policy/policyDialog.vue

external projects support collaborative mode;

feat: external projects support collaborative mode

---

src/components/projects/policy/policy.vue

fix: after modifying permissions, it prompts no changes

fix: after modifying permissions, it prompts no changes

---

src/components/common/workflowBuildRows.vue
src/components/common/workflowTestRows.vue
src/components/projects/workflow/productTaskDetail.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/test.vue

fix typo for better understanding
What's Changed: `环境变量` -> `变量`

fix typo for build/test variable

---

src/common/repoSelect.vue
src/components/projects/build/envVariable.vue
src/components/projects/build/otherSteps.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/buildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobCommonBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/otherSteps.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/jobOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stage.vue

custom workflow support builds

feat: custom workflow support builds

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/list/productRow.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/commonTask.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: support common task

---

src/components/micro/css/popover-pcc.less
src/components/micro/index.js
src/components/micro/index.vue
src/main.js
src/router/index.js

fix: styles for micro apps

---

src/api/index.js
src/components/enterprise/home.vue
src/components/enterprise/info.vue
src/components/enterprise/license.vue
src/components/entry/home/sidebar.vue
src/components/entry/home/topbar.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/router/index.js

add enterprise manage.
How it Works:

feat:add enterprise manage.

---

src/components/enterprise/info.vue
src/components/enterprise/license.vue
src/components/entry/home/sidebar.vue

fix:fix logo upload

---

src/components/enterprise/info.vue
src/components/entry/login.vue

fix:change logo in login page.

fix:change logo in login page.

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/workflowEditor/customWorkflow/jobOperate.vue

feat: add env tooltip in run custom workflow

feat: add env tooltip in run custom workflow

---

src/components/enterprise/license.vue

fix(typo):fix formate typo.

---

src/components/common/customWorkflowBuildRows.vue
src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/commonTask.vue
src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue
src/components/projects/workflow/productCustomTaskDetail/plugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/plugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: remove rsa in custom workflow

feat: remove rsa in custom workflow

---

config/index.js
src/components/entry/home/sidebar.vue
src/components/micro/index.vue

build: delete baseURL

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: add default branch in custom workflow

feat: add default branch in custom workflow

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomTaskDetail.vue

fix: scroll in custom workflow detail

fix: scroll in custom workflow detail

---

src/api/index.js
src/components/common/workflowBuildRows.vue
src/components/entry/home/sidebar.vue
src/components/projects/build/envVariable.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/approval.vue
src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/commonTask.vue
src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue
src/components/projects/workflow/productCustomTaskDetail/plugin.vue
src/components/projects/workflow/workflowEditor/commonWorkflow/modules/build.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
src/components/setting/plugins/manage.vue
src/components/templateLibrary/builds/envVariable.vue
src/router/index.js

feat: add plugin manage

---

src/api/index.js
src/components/projects/detail_ope/detail.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/env/pmEnv/createPmEnv.vue
src/components/release/environment/detail.vue
src/mobile/envs/envDetail.vue

feat:supports copy from existing environments.
How it Works:

feat:supports copy from existing environments.

---

src/api/index.js
src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/inner_env/changeLog.vue
src/components/projects/workflow/productTaskDetail/extension.vue
src/router/index.js

feat: environment support change log

feat: environment support change log

---

src/components/projects/env/helmEnv/createHelmEnv.vue

chore:remove useless code.

---

src/assets/css/component/service-detail.less
src/components/projects/env/inner_env/serviceDetail.vue

feat: download file from container

feat: download file from container

---

src/components/micro/index.js
src/components/micro/index.vue
src/router/micro.js

fix: modify route title

---

src/components/projects/scanner/create.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/templateLibrary/builds/otherSteps.vue

chore:clean code.

---

src/api/index.js
src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

supports webhook in common workflow.
How it Works:

feat:supports webhook in common workflow.

---

src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js

fix:show tip when repo is seletced. 
How it Works:

fix:show tip when repo is seletced. 

---

src/components/common/customWorkflowBuildRows.vue

fix:fix data watching bug.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

fix:fix view not updated.

---

src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/commonTask.vue
src/components/projects/workflow/productCustomTaskDetail/plugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

feat: add default build in job

feat: add default build in job 

---

src/components/projects/workflow/productCustomTaskDetail/buildConsole.vue
src/components/projects/workflow/productCustomTaskDetail/commonTask.vue
src/components/projects/workflow/productCustomTaskDetail/plugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

feat: cherry-pick 1080

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue

fix:supports gerrit in webhook.

fix:supports gerrit in webhook.

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: cherry-pick 1090

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: job added error

---

src/components/setting/imgs/manage.vue

fix:add trim to input.

---

src/utilities/wordTranslate.js

cluster status description is improper
What's Changed: update typo

fix typo: update the description for cluster status

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/plugin.vue

keep typo consistent
What's Changed: `是否加密` -> `敏感信息`

fix typo: keep typo consistent

---

src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

cherry-pick:#1101

---

src/components/projects/workflow/common/runCustomWorkflow.vue

fix: cherry-pick 1103

---

src/components/projects/workflow/common/runCustomWorkflow.vue

fix: don't show empty params

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue

fix: is_credential value conver  ******

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue

fix: cherry-pick 1105

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix:de-duplicate services based on service_module.

---

src/assets/css/component/env-detail.less
src/components/projects/common/importValues/treeFile.vue
src/components/projects/detail_ope/components/initEnvDialog.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/guide/helm/runtime.vue

fix: repo information saving error

cherry-pick 1109

---

src/assets/css/component/env-detail.less
src/components/projects/common/importValues/treeFile.vue
src/components/projects/detail_ope/components/initEnvDialog.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/guide/helm/runtime.vue

fix: repo information saving error

fix: repo information saving error

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
src/components/setting/integration/code.vue

fix: cherry-pick 1111

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix:check workflow data change before edit webhook

fix:check workflow data change before edit webhook

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix:get test by passing projectName.

fix:get test by passing projectName.

---

src/api/index.js
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue

fix:add projectName to webhook API.

---

src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue

fix: fix issue with updating global variables

fix: fix issue with updating global variables

---

src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1119

cherry pick 1119

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix:fix data comparison in webhook.

fix:fix data comparison in webhook.

---

src/components/common/customWorkflowCommonRows.vue
src/components/entry/login.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue

fix: clone

---

src/components/projects/common/importValues/repository.vue

fix:disable gitee when import values to service.

fix:disable gitee when import values to service.

---

src/components/common/customWorkflowBuildRows.vue

fix:fix branch not change when editing.

fix:fix branch not change when editing.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue

fix: is_credential false

---

src/components/entry/home/sidebar.vue
src/components/setting/plugins/manage.vue
src/router/index.js

fix: add help link in plugin manage

---

src/utilities/checkPermission.js

fix:remove public checking in permission.

fix:remove public checking in permission.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue

fix:fix webhook repos is undefined.

fix:fix webhook repos is undefined.

---

src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

feat:add skip_check_run_status to deploy job.

feat:add skip_check_run_status to deploy job.

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue

- don't show empty envs of freestyle and plugin type
- fix: replaceAll fixed
- fix: set default branch from build in product workflow

fix:fix multiple bugs.

---

src/components/projects/workflow/list/virtualListItem.vue

fix:fix permission binding action.

fix:fix permission binding action.

---

src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue

fix:fix property undefined.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix(style):fix style of label-width.

fix(style):fix style of label-width.

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: remove fixed when save fail

fix: remove fixed when save workflow fail

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue

fix: dont show empty plugin envs

fix: don't show empty plugin envs

---

src/components/projects/workflow/productCustomTaskDetail/deployConsole.vue

fix: deploy detail status color

fix: deploy detail status color

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

fix:fix variables not update.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/buildDeploy.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

solve the problem of duplication of components of different build services

fix:add filter to presets.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

feat:webhook supports task on/off switch. 

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

feat:webhook supports task on/off switch.

feat:webhook supports task on/off switch.

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/otherSteps.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

- env is not required in runtime type
- open shell autoly
- stage name is only

fix: fix minor bugs.

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/otherSteps.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

- env is not required in runtime type
- open shell autoly
- stage name is only

fix: cherry-pick 1158

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobServiceAndBuild.vue

fix: build env

---

src/api/index.js
src/components/entry/home/sidebar.vue

fix: sidebar error when admin switches regular members
fix: Intercept 404 requests from plutus

fix: sidebar error when admin switches regular members

---

src/components/projects/workflow/productTaskDetail/artifactDeploy.vue

fix:fix missing service link parameters.

fix:fix missing service link parameters.

---

src/components/setting/plugins/manage.vue

custome task link is 404
fix 404 link

fix typo: fix 404 link

---

src/components/setting/plugins/manage.vue

custome task link is 404
cherry-pick https://github.com/koderover/zadig-portal/pull/1166
fix 404 link

cherry-pick 1166: fix 404 link

---

src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

- using `service_module/service_name` as value-key in el-select
- adjust the service display mode to `service_module(service_name)` alignment with product workflow

fix:fix minor bugs in custom workflow.

---

src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobBuildEnv.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix:fix minor bugs in custom workflow. 

---

src/components/entry/home/sidebar.vue
src/components/micro/index.js
src/router/micro.js

feat:add release route.

---

src/components/entry/home/sidebar.vue

fix:disable release.

---

src/components/projects/workflow/workflowEditor/customWorkflow/stageOperate.vue

fix: stage name only

---

src/components/delivery/artifacts/detail.vue

fix:fix PR link in artifact tracing.

fix:fix PR link in artifact tracing.

---

src/components/entry/home/sidebar.vue
src/components/entry/home/topbar.vue
src/components/micro/index.js

- add /v1/release rule
- fix sidebar display error

fix: show bug

---

src/components/entry/home/sidebar.vue
src/components/entry/home/topbar.vue
src/components/micro/index.js

cherry-pick https://github.com/koderover/zadig-portal/pull/1180

cherry-pick 1180

---

src/components/common/customWorkflowCommonRows.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

fix:show repo tips when job's type is freestyle.

fix:show repo tips when job's type is freestyle.

---

src/components/projects/workflow/productCustomDetail.vue

fix: clone data reset
fix: clone data reset

fix: reset clone data 

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobCommonBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/plugin.vue

fix: validate error

---

src/components/projects/build/advancedConfig.vue

fix:fix cache validation in scanner config.

fix:fix cache validation in scanner config.

---

src/components/entry/home/sidebar.vue
src/components/micro/index.vue
src/components/projects/workflow/status/container/customWorkflowStatus.vue

feat: portal workflow status link plutus

feat: portal workflow status link plutus

---

src/common/host/importHosts.vue
src/common/host/manageHost.vue
src/components/entry/login.vue
src/components/projects/common/pm/addHost.vue
src/components/setting/cluster/manage.vue
src/components/setting/storage/manage.vue

add AWS Identifiers to Infrastructure.
- host management
- cluster management
- storage management

feat:add AWS Identifiers to Infrastructure. 

---

src/api/index.js
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/templateLibrary/k8s/fileAside.vue
src/components/templateLibrary/k8s/fileEditor.vue
src/components/templateLibrary/k8s/fileTree.vue
src/components/templateLibrary/k8s/index.vue

Optimize template variable configuration.
Editing configuration variables via YAML.

feat:optimize template variable configuration.

---

config/index.js

chore: clear useless code

---

src/store/modules/projectList.js

fix: breadcrumb show project name error

fix: breadcrumb show project name error

---

config/index.js
src/store/modules/projectList.js

cherry-pick https://github.com/koderover/zadig-portal/pull/1199

cherry-pick 1199

---

src/components/delivery/version/index.vue
src/components/delivery/version/k8s/detail.vue
src/components/projects/env/env_detail/envConfig/commonConfig.vue
src/components/projects/env/env_detail/envConfig/versionHistory.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/hostEnv/createHostEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/scanner/common/scannerRow.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/workflow/list/virtualListItem.vue

- [fix permission's tooltip when run scanner.](https://github.com/koderover/zadig-portal/pull/1194/commits/0129e71f372a58177e9790c09c801aadfdf5504d)
- [fix style of button.](https://github.com/koderover/zadig-portal/pull/1194/commits/a097c988dbd1020f1f6327633b059b7707d2439e)
- [fix tips after saving helm release.](https://github.com/koderover/zadig-portal/pull/1194/commits/cbdee2e224c139a3a87cde66a7091552f1e0e0d6)
- [checking user's role before update policy.](https://github.com/koderover/zadig-portal/pull/1194/commits/720f26bc232dbad14e09274b44da65d0d8862ccc)

fix:optimize permission-related ui issues.

---

src/common/host/manageHost.vue

fix:fix provider type in host management.

fix:fix provider type in host management.

---

src/components/projects/common/pm/addHost.vue

fix(typo):fix typo of type.

---

src/components/setting/registry/manage.vue

fix(typo):fix typo of deletion.

fix(typo):fix typo of deletion.

---

src/api/index.js
src/assets/css/component/service-mgr.less
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/editor/codeMirror.vue
src/components/projects/serviceMgr/helm/components/editor/folder.vue
src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/store/modules/serviceManage.js

feat:supports editing vaules.yaml.

feat:supports editing vaules.yaml.

---

src/components/projects/serviceMgr/helm/code.vue
src/store/modules/serviceManage.js

fix:fix tab changing bug in helm editor.

fix:fix tab changing bug in helm editor.

---

src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/env/env_detail/runWorkflow.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/common/pmArtifactDeploy.vue
src/components/projects/workflow/common/runWorkflow.vue

support for service updates via ops workflows.

fix:support for service updates via ops workflows.

---

src/api/index.js
src/components/setting/apps/manage.vue

fix:fix unenabled apps are not displayed

fix:fix disabled apps are not displayed.

---

package.json
yarn.lock

chore:bump version of vue-ace2-bind.

chore:bump version of vue-ace2-bind.

---

src/components/projects/test/common/function/functionDetail.vue
src/components/projects/test/function/functionSummary.vue
src/components/projects/test/function/functionTaskDetail.vue
src/components/projects/test/report/testCase.vue
src/router/index.js

fix:fix button issues caused by test links

fix:fix button issues caused by test links.

---

src/assets/css/component/service-mgr.less
src/components/projects/guide/helm/service.vue
src/components/projects/guide/k8s/service.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/serviceHost.vue
src/components/projects/serviceMgr/serviceK8s.vue
src/components/projects/workflow/productTaskDetail/artifactDeploy.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail/deploy.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
src/components/templateLibrary/builds/zadigBuild.vue

- [fix(style):fix style of onboarding.](https://github.com/koderover/zadig-portal/commit/8fb6cffd1a65cd49d7bab75bed4a2d8967eecd84)
- [fix(style):fix style of tooltip.](https://github.com/koderover/zadig-portal/commit/5861881eb7e0b4374c794c6dd49dc9154eacb18d)
- [fix(ux):close the dialog after saving.](https://github.com/koderover/zadig-portal/commit/efc6fe66a388288b74f9fe0e38a00f02589eef2f)

fix(ui):fix several user experience issues

---

src/components/entry/home/topbar.vue

style: topbar breadcrumb style

style: topbar breadcrumb style

---

src/components/projects/detail_ope/detail.vue

fix: error in getting data on project details page

fix: error in getting data on project details page

---

src/components/projects/env/env_detail/runWorkflow.vue

Workflow upgrade service supports regular filtering branches

feat:upgrade service supports regular filtering branches.

---

src/components/entry/home/topbar.vue

style: topbar popover style

---

src/components/projects/build/advancedConfig.vue
src/components/templateLibrary/builds/advancedConfig.vue

fix:fix the bug that the build can't be saved.

fix:fix the bug that the build can't be saved.

---

src/components/setting/announcement/manage.vue
src/router/index.js

feat(style):optimize announcement management style.

feat(style):optimize announcement management style. 

---

src/components/setting/cluster/manage.vue

we support tencentcloud EKS cluster, but it is not shown on portal for now.
What's Changed: add tencentcloud EKS for cluster management

add tencentcloud EKS for cluster management

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

fix webhook data not changed.
How it Works:

fix(webhook):fix webhook data not changed.

---

publish.sh
src/components/projects/policy/checkDiff.js
src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue

feat: collaborative mode supports custom workflows

feat: collaborative mode supports custom workflows

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue

fix(webhook):using cloned data to listen changed.

fix(webhook):using cloned data to listen changed.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobPlugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: add choice type in plugin job

 feat: add choice type in plugin job

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/env.vue

remove: unuseful code

---

src/api/index.js
src/components/projects/common/taskList.vue

fix: project name in clone workflow

---

src/components/projects/workflow/common/runCustomWorkflow.vue

fix: get branch in run custom workflow

fix: get branch in run custom workflow

---

src/store/modules/checkPlutus.js

fix: execution error when interface 404

fix: execution error when interface 404

---

src/mobile/project/env/common/mobileContainerLog.vue
src/mobile/project/env/helmServiceDetail.vue
src/mobile/project/env/k8sServiceDetail.vue

feat:support for displaying container logs on mobile.

feat:support for displaying container logs on mobile.

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

fix:fix gitlab branch search not working.

fix:fix gitlab branch search not working.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

make document link more accurate
revise document link in tooltip

fix typo: revise document link

---

src/api/index.js
src/components/entry/login.vue
src/main.js

fix: bug after adding permissions

fix: bug after adding permissions

---

amd64.Dockerfile

chore:add docker file label.

---

src/components/entry/home/sidebar.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobPlugin.vue
src/main.js
src/store/modules/checkPlutus.js

fix: only administrators can operate enterprise

fix: only administrators can operate enterprise

---

src/components/entry/home/sidebar.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobPlugin.vue
src/main.js
src/store/modules/checkPlutus.js

cherry-pick https://github.com/koderover/zadig-portal/pull/1243

cherry-pick 1243

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/mobile/project/workflow/product/common/runCustomWorkflow.vue

fix: set default service when only one service

fix: set default service when only one service

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue

fix: repos undefined

---

src/common/cusTags.vue
src/components/projects/workflow/productCustomTaskDetail/jobDeployDetail.vue

fix: remove unuseful icon

---

src/components/common/customWorkflowBuildRows.vue

feat: add test name in run customWorkflow

feat: add test name in run customWorkflow

---

src/components/projects/serviceMgr/k8s/serviceEditor.vue

fix(gitee):fix editor is editable when the source is gitee.

fix(gitee):fix editor is editable when the source is gitee.

---

src/api/index.js
src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

feat:add timer to trigger configuration.
How it Works:

feat:add timer to trigger configuration.

---

static/site.webmanifest

fix:fix web manifest icon path.

fix:fix web manifest icon path.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix(webhook):get repo data through other API.

fix(webhook):get repo data through other API.

---

src/components/common/customWorkflowBuildRows.vue
src/components/common/workflowBuildRows.vue
src/components/projects/scanner/common/runScannerTask.vue
src/components/projects/test/common/function/container/advancedConfig.vue
src/components/projects/test/common/function/functionDetail.vue

feat: set default branch in other repo
feat: ui

feat: set default branch in other repo

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

fix: webhook env

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix:check the build name before getting the repo.

fix:check the build name before getting the repo.

---

src/api/index.js
src/components/common/artifactDownload.vue
src/components/entry/login.vue
src/components/projects/test/report/productWorkflowTestCase.vue

fix: add projectName

---

src/components/projects/common/integrationRegistry.vue
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/setting/integration/code.vue
src/components/setting/integration/components/sonarOperate.vue
src/components/setting/integration/jira.vue
src/components/setting/integration/other.vue
src/components/setting/registry/manage.vue

fix:remove URL validation to support custom domains.

fix:remove URL validation to support custom domains.

---

src/components/projects/test/common/function/container/taskDetailTest.vue
src/components/projects/test/common/function/functionTaskDetail.vue

fix:fix test details log isn't displayed immediately when opened.

fix:fix test details log isn't displayed immediately when opened.

---

src/mobile/project/detail.vue
src/mobile/project/test/detail.vue
src/mobile/project/test/runWorkflow.vue
src/mobile/project/test/taskDetail.vue
src/mobile/project/workflow/product/common/taskDetailTest.vue
src/mobile/project/workflow/product/taskDetail.vue
src/mobile/project/workflow/status.vue
src/router/index.js
src/utilities/utilities.js

feat:support for running and viewing tests in projects.

feat:support for running and viewing tests in projects.

---

src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue

feat: job detail css

---

config/index.js
src/components/projects/workflow/common/runCustomWorkflow.vue

cherry-pick: 1264

---

src/components/setting/apps/manage.vue

feat:Optimized UI of application management list.

feat:Optimized UI of application management list.

---

src/components/micro/css/dialog-webhook.less
src/components/micro/index.vue

fix(style):fix style in micro app.

fix(style):fix style in micro app.

---

src/components/micro/css/dialog-webhook.less

fix:fix style of child app.

---

src/components/micro/css/dialog-webhook.less

fix:fix style in el-form.

---

src/components/micro/css/dialog-webhook.less
src/components/micro/index.vue

cherry-pick:#1272

---

src/components/projects/common/integrationRegistry.vue
src/components/setting/registry/manage.vue

fix(typo):fix typo in registry management.
How it Works:

fix(typo):fix typo in registry management.

---

src/mobile/project/workflow/product/common/k8sArtifactDeploy.vue
src/mobile/project/workflow/product/common/pmArtifactDeploy.vue

fix:limit the length of service names on mobile.

fix:limit the length of service names on mobile.

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix:fix repo is undefined when build of the service doesn't exist.

fix:fix repo is undefined when build of the service doesn't exist.

---

src/components/entry/components/signUp.vue
src/components/projects/common/integrationRegistry.vue
src/components/setting/apps/manage.vue
src/components/setting/config/link.vue
src/components/setting/config/mail.vue
src/components/setting/config/proxy.vue
src/components/setting/helm/manage.vue
src/components/setting/integration/account.vue
src/components/setting/integration/code.vue
src/components/setting/integration/components/addJenkins.vue
src/components/setting/integration/components/sonarOperate.vue
src/components/setting/integration/jira.vue
src/components/setting/integration/other.vue
src/components/setting/storage/manage.vue

fix:triming spaces in address-related input.
- Package Management -> Installation Package Address
- Code Source Integration -> Service URL
- Account System Integration -> Host Address
- Jenkins Integration -> Service URL
- Jira Integration -> Jira Address
- Sonar Integration -> Service Address
- Other System Integration -> Access Address
- Object Storage  ->  Access Point Addresses
- HELM repository -> URL
- Proxy Configuration -> Server Address
- Quick Links -> URL
- Mail Configuration -> Host
- Mail Configuration -> Sender Address
- User Registration -> Mailbox

fix:triming spaces in address-related input.

---

src/api/index.js
src/components/delivery/version/k8s/detail.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/list/virtualListItem.vue

add view api projecName
validate workflow name

fix: add view api projecName

---

src/common/cusTags.vue

fix: cusTags component vertical-align middle

fix: cusTags component vertical-align middle

---

src/components/projects/workflow/productTaskDetail.vue

fix: add display_name in product workflow test report

fix: add display_name in product workflow test report

---

src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/common/serviceTree.vue

fix:fix data synchronization error when import service  from template.

fix:fix data synchronization error when import service  from template.

---

src/store/modules/login.js

fix: enterprise page 404

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue

fix: product workflow can't change tab

fix: product workflow can't change tab

---

src/components/setting/integration/githubApp.vue

fix(link):fix doc link.

---

src/components/entry/home.vue
src/components/entry/home/floatLink.vue

feat: float link ui

---

src/api/index.js
src/assets/css/common/common.less
src/components/entry/home/subTopbar.vue
src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/varGroups.vue
src/components/projects/detail_ope/components/initEnvDialog.vue
src/components/projects/detail_ope/initialize.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/group/create.vue
src/components/projects/group/index.vue
src/components/projects/guide/helm/runtime.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
src/router/index.js

feat: helm project can add variables group
feat: add variableSet type when importing Helm values file

 feat: helm project can add variables group

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue

feat: add reg branch in webhook

feat: add reg branch in custom workflow webhook

---

src/components/projects/workflow/list.vue

fix(style):fix style of button size.

fix(style):fix style of button size.

---

src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/varGroups.vue

fix: value content is set to empty
fix: avoid requesting variable group data without permission

fix: variable groups for the helm project

---

src/api/index.js
src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/common/gitFileTree.vue
src/components/common/testTrigger.vue
src/components/common/workflowBuildRows.vue
src/components/delivery/artifacts/detail.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/scanner/common/runScannerTask.vue
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitFileTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/workflow/common/repoJump.vue
src/components/projects/workflow/common/runWorkflow.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
src/components/setting/integration/code.vue
src/components/setting/plugins/manage.vue
src/components/templateLibrary/chart/importChart.vue
src/mobile/project/workflow/product/common/workflowBuildRows.vue
src/mobile/project/workflow/product/runWorkflow.vue

feat:add new git provider. 

---

src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue

feat: add filterable attr in registry list

feat: add filterable attr in registry list

---

src/components/projects/test/common/function/container/testRow.vue

fix:fix link in test center.

---

src/components/entry/home.vue

fix: float link css

---

src/components/projects/detail_ope/home.vue

project list interface supports search

feat: project list interface supports search

---

patches/element-ui+2.15.10.patch
src/components/common/customWorkflowBuildRows.vue
src/components/common/customWorkflowCommonRows.vue
src/components/common/workflowBuildRows.vue
src/components/projects/scanner/common/runScannerTask.vue
src/mobile/project/workflow/product/common/workflowBuildRows.vue

feat:optimize drop-down box for new branch entries.
How it Works:

feat:optimize drop-down box for new branch entries.

---

src/components/entry/home.vue
src/components/projects/detail_ope/home.vue
src/components/projects/scanner/create.vue
src/components/projects/test/common/function/container/testRow.vue

feat: add some fileds in scanner code

feat: add some fileds in scanner code

---

config/index.js
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobFreestyle.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: optimize job

---

src/components/projects/build/advancedConfig.vue
src/components/templateLibrary/builds/advancedConfig.vue

feat: operating system supports GPU

feat: operating system supports GPU

---

src/components/projects/workflow/common/runCustomWorkflow.vue

fix: close div

---

src/components/projects/common/codemirror.vue
src/components/setting/cluster/manage.vue

feat: scheduling policy support tolerance

feat: scheduling policy support tolerance

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

feat:show type on git provider's namespace.

feat:show type on git provider's namespace.

---

src/components/projects/scanner/create.vue
src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue

fix: set the link to disable if the url doesn‘t exist.

fix: set the link to disable if the url doesn‘t exist.

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

feat:using local data when searching namespace from special provider.
How it Works:

feat:using local data when searching namespace from special provider.

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: not request custom workflow detail api when workflow fails

feat: don't request workflow detail api when other api get error.

---

src/components/projects/workflow/common/repoJump.vue
src/components/projects/workflow/commonTaskDetail.vue

[fix:fix commit link.](https://github.com/koderover/zadig-portal/commit/8cc3cb36d94b8865819da0b3e947151e2ed71784)

fix:fix commit link. 

---

src/components/projects/scanner/common/runScannerTask.vue

fix:fix repo_namespace is missing.

fix:fix repo_namespace is missing.

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue

fix:using path to search.

---

src/components/projects/scanner/create.vue
src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue

fix: ui enhance

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

feat: wechat can notify some people

---

src/components/projects/serviceMgr/common/serviceTree.vue

fix:add label to repoOwner.

---

src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue

fix:fix namespace is undefined.

fix:fix namespace is undefined.

---

src/api/index.js

fix:fix redirect query is missing when token is expired.

fix:fix redirect query is missing when token is expired.

---

src/components/entry/home/topbar.vue

fix: Chinese products in customer deliveries cannot be deleted

fix: Chinese products in customer deliveries cannot be deleted

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

feat: feishu can notify some people

---

src/assets/css/common/scroll-bar.less
src/components/entry/home/sidebar.vue

feat:optimize sidebar scrollbar style.

feat:optimize sidebar scrollbar style.

---

src/components/entry/home/sidebar.vue

feat:change color of scrollbar.

feat:change color of scrollbar.

---

src/components/projects/detail_ope/home.vue

fix(style):right alignment of project’s buttons.
How it Works:

fix(style):right alignment of project’s buttons.

---

src/components/projects/serviceMgr/common/integrationCode.vue
src/components/setting/integration/code.vue

fix(typo):fix typo of app permission.

fix(typo):fix typo of app permission.

---

src/components/entry/home/common/notification.vue
src/components/entry/home/topbar.vue

feat(style):change style of topbar.

feat(style):change style of topbar. 

---

src/assets/css/theme/index.css
src/common/cusTags.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/list/productRow.vue
src/utilities/utilities.js

feat(ui):optimize workflow list.

feat(ui):optimize workflow list. 

---

src/components/projects/detail_ope/detail.vue

fix(icon):fix project's loading icon.

fix(icon):fix project's loading icon.

---

src/components/entry/home/common/docLink.vue
src/components/entry/home/topbar.vue

chore:document links as a component.

chore:document links as a component.

---

src/components/projects/detail_ope/detail.vue
src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/productCustomDetail.vue
src/components/projects/workflow/productDetail.vue

fix(workflow):fix custom workflow issues and clean code.

fix(workflow):fix custom workflow issues and clean code.

---

src/api/index.js
src/components/projects/workflow/list.vue
src/components/projects/workflow/list/productRow.vue

feat(ux):optimize workflow view component.

feat(ux):optimize workflow view component.

---

config/index.js
src/api/index.js
src/components/projects/workflow/list.vue
src/components/templateLibrary/workflows/index.vue

feat: workflow template

---

src/components/projects/workflow/list.vue

fix: hide new workflow entry in portal

---

config/index.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/templateLibrary/workflows/components/jobs/jobDeploy.vue

fix: add display_name query field when create workflow

---

src/components/projects/build/advancedConfig.vue
src/components/projects/build/zadigBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobFreestyle.vue
src/components/templateLibrary/builds/advancedConfig.vue

feat: some builds support using the host Docker Daemon

feat: some builds support using the host Docker Daemon

---

src/components/projects/workflow/list.vue
src/components/templateLibrary/common/subTopbar.vue
src/components/templateLibrary/workflows/index.vue

fix:disable other workflow type.

fix:disable other workflow type.

---

src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sResourceUpdate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/setting/integration/code.vue
src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue
src/components/templateLibrary/workflows/config.vue
src/components/templateLibrary/workflows/index.vue
src/components/templateLibrary/workflows/item.vue

fix(typo):fix typo.

---

src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue

fix:fix comp is not show.

---

src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobGrayRollback.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sGrayDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sResourceUpdate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue

fix:fix projectName prop.

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/templateLibrary/workflows/components/jobs/jobBuild.vue

fix: model detail handle env

---

src/components/projects/workflow/list.vue
src/components/templateLibrary/common/subTopbar.vue
src/components/templateLibrary/workflows/index.vue

Reverts koderover/zadig-portal#1361

Revert "fix:disable other workflow type."

---

src/api/index.js
src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/common/importValues/treeFile.vue
src/components/projects/common/mixin/importRepo.js
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/templateLibrary/chart/importChart.vue

feat:import yamls from other git provider.

feat:import yamls from other git provider.

---

src/api/index.js
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
src/components/setting/integration/code.vue

fix:change workflow's page size to 500.

fix:change workflow's page size to 500. 

---

src/components/projects/common/mixin/importRepo.js
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue

fix:fix codeSource is undefined.

fix:fix codeSource is undefined.

---

src/components/projects/workflow/productCustomTaskDetail/jobDeployDetail.vue
src/components/templateLibrary/workflows/config.vue
src/components/templateLibrary/workflows/index.vue

fix: keep workflow type status when create workflow template

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/jobs/jobBuild.vue

fix:assign template data to init payload.

fix:assign template data to init payload.

---

src/components/projects/workflow/list/virtualListItem.vue

fix: successRate in workflow list

---

config/index.js
src/api/index.js
src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/canInput.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/canInput.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobGrayRollback.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sGrayDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sResourceUpdate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/config.js
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/jobs/jobBlueGreenConfirm.vue
src/components/templateLibrary/workflows/components/jobs/jobBlueGreenDeploy.vue
src/components/templateLibrary/workflows/components/jobs/jobCanaryConfirm.vue
src/components/templateLibrary/workflows/components/jobs/jobCanaryDeploy.vue
src/components/templateLibrary/workflows/components/jobs/jobGrayRollback.vue
src/components/templateLibrary/workflows/components/jobs/jobK8sGrayDeploy.vue
src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue

fix: add projectName in template list

---

config/index.js
src/components/common/testTrigger.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix: repo can't select branch

---

config/index.js
src/components/common/testTrigger.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix: cherry-pick 1372

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobBlueGreenConfirmDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobBlueGreenDeployDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobCanaryConfirmDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobCanaryDeployDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobGrayRollbackDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobK8sGrayDeployDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobK8sResourceUpdateDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBlueGreenDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryConfirm.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobCanaryDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sGrayDeploy.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sResourceUpdate.vue
src/components/templateLibrary/workflows/components/jobs/jobBlueGreenDeploy.vue
src/components/templateLibrary/workflows/components/jobs/jobCanaryConfirm.vue
src/components/templateLibrary/workflows/components/jobs/jobCanaryDeploy.vue
src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue

fix:fix minor bugs.

---

src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue

fix:don't check yaml in template lib.

fix:don't check yaml in template lib.

---

src/components/templateLibrary/workflows/config.vue

fix: remove yaml check in template library

fix: remove yaml check in template library

---

src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue

feat: notify somebody only in plutus and modify tips

---

src/components/entry/home.vue

fix(link):fix smtp link url.

---

src/components/templateLibrary/builds/fileAside.vue

feat:add link to build name.

---

src/common/serviceRepoSelect.vue
src/components/projects/build/zadigBuild.vue

repo supports bulk import
How it Works:

feat:repo supports bulk import.

---

src/api/index.js
src/components/projects/env/env_detail/components/updateHelmVarDialog.vue

fix:fix values path is undefined.

fix:fix values path is undefined.

---

src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/components/chartList.vue

fix:fix valuesPath not show when edit service.

fix:fix valuesPath not show when edit service.

---

src/components/entry/home/sidebar.vue

[feat:disable sidebar menu.](https://github.com/koderover/zadig-portal/commit/34fa15bfffd7a263f96c4e777cc41ed27a70c97d)

feat:disable sidebar menu.

---

src/common/serviceRepoSelect.vue

feat:add checking to bulk import.

feat:add checking to bulk import.

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/canInput.vue
src/components/templateLibrary/workflows/config.vue

fix:add limit to tooltip length

fix:add limit to tooltip length

---

src/common/serviceRepoSelect.vue

feat:get namesapce data from cache when data is duplicate.

feat:get namesapce data from cache when data is duplicate.

---

src/components/projects/serviceMgr/common/integrationCode.vue
src/components/setting/integration/code.vue

fix:fix redirect's query is missing.

fix:fix redirect's query is missing.

---

src/components/setting/integration/components/configManage.vue

fix: placeholder for service address

fix: placeholder for service address

---

config/index.js
src/components/common/customWorkflowBuildRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomTaskDetail/jobBuildDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notify.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/envTypeSelect.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/notify.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/envTypeSelect.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/envTypeSelect.vue
src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
src/components/templateLibrary/workflows/components/jobs/jobTest.vue

fix: share global vars between  jobs

---

src/api/index.js
src/components/entry/home/subTopbar.vue

feat: switching of managed projects to K8s YAML projects

feat: switching of managed projects to K8s YAML projects

---

src/components/projects/env/env_detail/components/manageK8sServicesDialog.vue
src/components/projects/serviceMgr/common/checkResource.vue
src/components/projects/serviceMgr/serviceK8s.vue

- when creating a new service, add resource detection

feat: when creating a new service, add resource detection

---

src/components/projects/workflow/productTaskDetail.vue

fix: display_name undefined

---

src/components/projects/workflow/productTaskDetail.vue

fix: cherry-pick 1408

---

src/components/projects/env/env_detail/components/updateHelmVarDialog.vue

fix:fix gitRepoConfig is undefined.

fix:fix gitRepoConfig is undefined.

---

src/components/projects/workflow/list/workflowRow.vue

fix(style):fix workflow desc style.

---

src/assets/css/component/env-detail.less
src/assets/css/component/service-mgr.less
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1409

cherry pick  1409

---

src/components/projects/serviceMgr/common/serviceTree.vue

fix:fix permission tooltip.

---

src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/serviceMgr/serviceK8s.vue

fix: enhance environment

---

src/components/projects/env/env_detail/components/serviceList.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1421

cherry pick 1421

---

config/index.js
src/api/index.js
src/assets/css/quote/iconfont.css
src/components/projects/build/advancedConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/settings.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/settings.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobFreestyle.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobPlugin.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobScanning.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/setting/cluster/manage.vue
src/components/templateLibrary/workflows/components/base/settings.vue
src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
src/components/templateLibrary/workflows/components/jobs/jobFreestyle.vue
src/components/templateLibrary/workflows/components/jobs/jobPlugin.vue
src/components/templateLibrary/workflows/components/jobs/jobScanning.vue
src/components/templateLibrary/workflows/components/jobs/jobTest.vue
src/components/templateLibrary/workflows/config.vue

feat: support share storage between custom workflow jobs

---

config/index.js
src/api/index.js
src/assets/css/quote/iconfont.css
src/components/projects/build/advancedConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/settings.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/settings.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobFreestyle.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobPlugin.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobScanning.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/setting/cluster/manage.vue
src/components/templateLibrary/workflows/components/base/settings.vue
src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
src/components/templateLibrary/workflows/components/jobs/jobFreestyle.vue
src/components/templateLibrary/workflows/components/jobs/jobPlugin.vue
src/components/templateLibrary/workflows/components/jobs/jobScanning.vue
src/components/templateLibrary/workflows/components/jobs/jobTest.vue
src/components/templateLibrary/workflows/config.vue

cherry-pick 1407

---

src/components/delivery/version/container/runWorkflow.vue
src/components/delivery/version/k8s/detail.vue
src/components/projects/workflow/productTaskDetail.vue

cherry pick:#1423
How it Works:

fix:fix displayName and service component issues.

---

src/components/projects/serviceMgr/common/serviceTree.vue

fix(style):fix style of tag.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue

fix: only plutus can apply all service

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue

cherry-pick 1427

---

config/index.js
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue

fix:check  target_tag when run custom workflow

---

config/index.js
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue

cherry-pick 1429

---

src/components/projects/workflow/common/runCustomWorkflow.vue

cherry-pick 1432 

---

src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/k8sPmEnv/k8sServiceList.vue

feat: services are not editable when importing only services

feat: services are not editable when importing only services

---

src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/k8sPmEnv/k8sServiceList.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1435

cherry pick 1435

---

src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/serviceK8s.vue

Service - join the environment, release restrictions and initialize environment values

feat: service - join the environment

---

src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/serviceK8s.vue

cherry-pick https://github.com/koderover/zadig-portal/pull/1437

cherry pick 1437

---

src/components/projects/policy/policy.vue
src/components/projects/policy/policyDialog.vue

fix(style):fix style of policy di
How it Works:

fix(style):fix style of policy dialog.

---

src/components/projects/serviceMgr/common/integrationCode.vue
src/components/setting/integration/code.vue

feat:Add newline to the end of the ssh key.

feat:Add newline to the end of the ssh key.

---

src/components/entry/home/sidebar.vue
src/components/projects/scanner/create.vue
src/components/setting/imgs/manage.vue
src/router/index.js

feat: sonar support for using custom build images

feat: sonar support for using custom build images

---

src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/components/serviceList.vue

feat: the service displays an error message

feat: the service displays an error message

---

src/api/index.js
src/components/profile/manage.vue

feat:support modify mailbox.

---

src/components/projects/detail_ope/components/deleteProject.vue
src/components/projects/detail_ope/home.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add translation to projects.

translation:add translation to projects.

---

src/components/setting/auditlog/manage.vue
src/lang/en.js
src/lang/zh-CN.js

transaltion:add translation to audit log.

transaltion:add translation to audit log.

---

src/components/setting/imgs/manage.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add translation to images.

translation:add translation to images.

---

src/components/setting/storage/manage.vue

feat:provider aws supports 'region' prop.

feat:provider aws supports 'region' prop.

---

src/components/setting/storage/manage.vue

feat:aws supports region prop.

feat:aws supports region prop.

---

src/components/projects/workflow/status/container/customWorkflowStatus.vue
src/components/projects/workflow/status/container/productWorkflowStatus.vue
src/components/projects/workflow/status/container/scannerStatus.vue
src/components/projects/workflow/status/container/testStatus.vue
src/components/projects/workflow/status/status.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add translation to status.

translation:add translation to status.

---

src/components/projects/detail_ope/initialize.vue
src/components/projects/env/env_detail/components/shareEnvDialog.vue
src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/workflow/productTaskDetail/filterStatus.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/confirmJobDialog.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/confirmJobDialog.vue
src/components/setting/config/link.vue
src/components/setting/integration/home.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add global translation.

translation:add global translation.

---

src/api/index.js
src/components/profile/info.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/setting/integration/components/addJenkins.vue
src/components/setting/integration/components/configManage.vue
src/components/setting/integration/components/sonarOperate.vue
src/components/setting/integration/configManage.vue
src/components/setting/integration/jenkins.vue
src/components/setting/integration/sonar.vue
src/components/templateLibrary/workflows/components/stageOperate.vue
src/components/templateLibrary/workflows/config.vue

merger main into i18n.
- [] No code

merge:sync branch main to i18n.

---

config/index.js
src/components/common/testTrigger.vue
src/components/projects/test/common/function/container/advancedConfig.vue
src/components/projects/test/common/function/container/taskDetailTest.vue
src/components/projects/test/common/function/container/testRow.vue
src/components/projects/test/common/function/function.vue
src/components/projects/test/common/function/functionDetail.vue
src/components/projects/test/common/function/functionSummary.vue
src/components/projects/test/common/function/functionTaskDetail.vue
src/components/projects/test/common/functionTestCase.vue
src/components/projects/test/common/functionTestSummary.vue
src/components/projects/test/common/report/testCase.vue
src/lang/en.js
src/lang/zh-CN.js

translation: testing

---

src/components/projects/serviceMgr/common/checkResource.vue

feat: add variable configuration to resource monitoring

---

src/common/variablePreviewEditor.vue
src/components/projects/common/importConfig/index.vue
src/components/projects/common/importValues/index.vue
src/components/projects/env/env_detail/common/envConfig.vue
src/components/projects/env/env_detail/envConfig/home.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/env/k8sPmEnv/k8sServiceList.vue
src/components/projects/env/k8sPmEnv/varList.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add translation to env creation.

translation:add translation to env creation. 

---

src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/env/pmEnv/createPmEnv.vue

translation:add transaltion to loading.

translation:add transaltion to loading.

---

src/components/projects/common/hosting/addHostEnv.vue
src/components/projects/common/importValues/keyValue.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
src/components/projects/env/helmEnv/createHelmEnv.vue
src/components/projects/env/hostEnv/createHostEnv.vue
src/components/projects/env/hostEnv/editExternalConfig.vue
src/components/projects/env/hostEnv/editHostService.vue
src/components/projects/env/pmEnv/createPmEnv.vue
src/components/projects/serviceMgr/common/checkResource.vue
src/lang/en.js
src/lang/zh-CN.js

translation:add translation to helm and hosing env creation.

translation:add translation to helm and hosing env creation.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
src/components/templateLibrary/workflows/components/stageOperate.vue
src/components/templateLibrary/workflows/config.vue

fix: delete unuseful approval_users fields

---

src/components/projects/workflow/productCustomTaskDetail/jobBuildDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobImageDistributeDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue

feat: get log when status is running

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/config.js
src/components/templateLibrary/workflows/config.js

feat: notify add created type

---

src/components/templateLibrary/chart/aside.vue

fix:fix bar style in en mode.

---

src/components/projects/build/buildEnv.vue
src/components/projects/build/config.vue

[fix:fix key undefined.](https://github.com/koderover/zadig-portal/commit/9afa94e0f2a2d8ee2e373c6c3a1b1c331b2c438e)

fix:fix key undefined. 

---

src/components/projects/common/importValues/repository.vue
src/components/projects/detail_ope/home.vue
src/components/projects/scanner/create.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/lang/en.js
src/lang/zh-CN.js

feat: add doc link

---

.vscode/settings.json
src/components/projects/env/inner_env/home.vue
src/components/projects/env/k8sPmEnv/varYaml.vue
src/components/projects/serviceMgr/serviceK8s.vue
src/lang/en.js
src/lang/zh-CN.js
src/router/index.js

fix: variable bug

---

src/components/projects/policy/policyDialog.vue

fix:fix $t is undefined.
How it Works:

fix:fix $t is undefined.

---

src/common/host/manageHost.vue
src/components/delivery/common/subTopbar.vue
src/components/entry/home/sidebar.vue
src/components/entry/home/subTopbar.vue
src/components/projects/detail_ope/home.vue
src/components/projects/policy/policyDialog.vue
src/components/projects/scanner/create.vue
src/components/projects/serviceMgr/k8s/container/policy.vue
src/components/projects/workflow/common/k8sArtifactDeploy.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/setting/cluster/manage.vue
src/mobile/project/workflow/product/common/k8sArtifactDeploy.vue

[fix(style):fix style of typo.](https://github.com/koderover/zadig-portal/commit/a6c1dd5f718f3668a3177952b118f6794602a964)

fix(style):fix style of typo.

---

src/components/projects/workflow/list/workflowRow.vue

feat(style):change style of workflow list.

feat(style):change style of workflow list.

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/lang/zh-CN.js

clean:clean code

---

src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/lang/en.js
src/lang/zh-CN.js

fix:fix i18n.

---

src/components/projects/workflow/workflowEditor/customWorkflow/config.js

fix:fix i18n key.

---

src/components/setting/integration/home.vue
src/components/setting/users/components/roleOperate.vue

tooltip:add tooltip. 
How it Works:

tooltip:add tooltip. 

---

src/components/setting/integration/home.vue

tooltip:add tooltip.

---

src/assets/css/common/common.less

fix: modify disabled color

---

src/components/setting/users/components/roleOperate.vue

fix:fix filter not work.

---

src/components/projects/common/importValues/index.vue
src/components/projects/common/importValues/repository.vue
src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
src/components/projects/scanner/create.vue
src/components/projects/serviceMgr/k8s/container/policy.vue

fix: css and link

---

src/components/templateLibrary/builds/advancedConfig.vue

fix: disabled docker daemon

---

src/components/projects/serviceMgr/common/integrationCode.vue
src/components/setting/integration/code.vue

fix:checking ssh key before add new line.

fix:checking ssh key before add new line.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/k8s/serviceEditor.vue
src/components/projects/serviceMgr/serviceK8s.vue
src/components/templateLibrary/k8s/fileAside.vue
src/components/templateLibrary/k8s/fileEditor.vue

[fix:fix minor bugs in variables.](https://github.com/koderover/zadig-portal/commit/93ec8a62fac1deac542ab507efa591cdcff508e8)

fix:fix minor bugs in variables. 

---

src/assets/css/common/common.less
src/assets/css/theme/index.css
src/components/delivery/common/subTopbar.vue
src/components/entry/home/sidebar.vue
src/components/entry/home/subTopbar.vue

fix(style):fix color of disabled.

fix(style):fix color of disabled.

---

src/lang/en.js
src/lang/zh-CN.js

fix:fix typo.

---

src/components/projects/guide/k8s/delivery.vue

fix: generate k8s pipelines

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue

fix:fix redirect when edit webhook.

fix:fix redirect when edit webhook.

---

src/common/testTimer.vue
src/components/projects/dashboard.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/productCustomDetail.vue
src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

fix: minor bugs

---

src/components/projects/workflow/list.vue

fix(style):change dialog width.

fix(style):change dialog width.

---

src/components/templateLibrary/k8s/fileAside.vue

fix:fix data update in slot.

---

src/components/projects/serviceMgr/helm/components/common/gitRepo.vue

fix: repo attribute's label

---

src/components/templateLibrary/chart/importChart.vue

fix:fix codehost id is undefined.

fix:fix codehost id is undefined.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

fix:disable edit when service is shared service.

fix:disable edit when service is shared service.

---

src/components/templateLibrary/k8s/fileAside.vue

fix:fix variable not update.

---

src/common/host/manageHost.vue
src/components/projects/common/integrationRegistry.vue
src/components/setting/registry/manage.vue
src/lang/en.js
src/lang/zh-CN.js

feat: modify description

---

src/components/projects/serviceMgr/k8s/serviceEditor.vue

fix:fix jsyaml load error.

---

src/components/setting/cluster/manage.vue
src/components/setting/registry/manage.vue

fix: manage bug

---

src/components/common/testTrigger.vue

fix: translate workflow

---

src/components/projects/serviceMgr/common/serviceTree.vue
src/components/projects/serviceMgr/serviceK8s.vue

[fix:get varibale_yaml from other prop.](https://github.com/koderover/zadig-portal/commit/1124e7c8aabbaaecb3ee0e5e1d24bf0adc5d7e40)

fix:get varibale_yaml from other prop. 

---

src/components/setting/cluster/manage.vue

fix: update description

---

src/components/projects/serviceMgr/serviceK8s.vue

fix:fix upgrade env.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/templateLibrary/k8s/fileAside.vue

fix:fix boolean not show.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue
src/components/projects/serviceMgr/serviceK8s.vue

fix:update service list after save variables.
How it Works:

fix:update service list after save variables.

---

src/components/projects/common/mixin/importRepo.js

fix:clean origin namespace when change provider.

fix:clean origin namespace when change provider.

---

src/components/projects/dashboard.vue

fix: dashboard css

---

src/components/projects/dashboard.vue

fix: workflow name

---

src/components/projects/dashboard.vue

fix: icon css

---

src/common/testTimer.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue
src/lang/en.js
src/lang/zh-CN.js

fix: translate

---

src/components/projects/env/env_detail/components/updateK8sVarDialog.vue

fix: change update icon

---

src/components/setting/cluster/manage.vue

fix:fix component is not found.

fix:fix component is not found.

---

src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

fix: trim product workflow name

---

src/components/profile/info.vue

fix:fix ref is undefined.

---

src/components/projects/workflow/list.vue
src/lang/en.js
src/lang/zh-CN.js

fix:fix workflow deletion typo.

fix:fix workflow deletion typo.

---

src/components/projects/workflow/list.vue

fix:fix cutom workflow deletion tip.

fix:fix cutom workflow deletion tip.

---

src/App.vue

chore:update console info.
How it Works:

chore:update console info.

---

src/api/index.js
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue

fix:change request method to get build config.

fix:change request method to get build config. 

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: disable workflow name

---

src/components/projects/serviceMgr/serviceK8s.vue

fix:add tooltip when variable is empty.

fix:add tooltip when variable is empty.

---

src/components/entry/home/topbar.vue

fix:searching project by alias.

 fix:searching project by alias.

---

src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: replace cancel to close

---

src/components/entry/home.vue
src/components/setting/config/home.vue

fix:fix smtp link.

---

src/components/entry/home.vue

fix:fix announcement z-index.

---

src/components/projects/detail_ope/home.vue

fix:fix i18n in project list.

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: workflow job add 'run policy'

---

src/components/projects/serviceMgr/helm/code.vue
src/store/modules/serviceManage.js

feat: optimization of helm's service management

feat: optimization of helm's service management

---

src/components/projects/serviceMgr/helm/code.vue
src/components/projects/serviceMgr/helm/components/editor/folder.vue

style: optimize service focus

---

config/index.js
src/components/projects/workflow/list/workflowRow.vue
src/lang/en.js
src/lang/zh-CN.js

feat: support favorite workflow

---

src/components/projects/workflow/productCustomTaskDetail/stageApproval.vue

fix: approval timeout

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: workflow job disappear when cancel job 

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: set active style of workflow job

---

src/lang/en.js
src/lang/zh-CN.js
src/utilities/wordTranslate.js

feat: support waitforapproval status in workflow

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: job active style in workflow detail

---

src/components/setting/registry/manage.vue

fix: validate registry url 

---

src/components/projects/workflow/productCustomTaskDetail/jobBuildDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobDeployDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobImageDistributeDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobK8sDeployDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobK8sResourceUpdateDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobPluginDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue
src/components/projects/workflow/productTaskDetail/artifactDeploy.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail/deploy.vue
src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
src/components/projects/workflow/productTaskDetail/extension.vue
src/components/projects/workflow/productTaskDetail/test.vue

feat: error msg support wrap

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: webhook confirm dialog

---

src/components/entry/home/topbar.vue

feat:move breadcrumb to the back of project.

feat:move breadcrumb to the back of project.

---

src/api/index.js
src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/common/chromeTabs.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/workflow/list/workflowRow.vue

feat: environmental support favorites

feat: environmental support favorites

---

src/common/xtermLog.vue
src/components/projects/scanner/common/taskDetailScanner.vue
src/components/projects/test/common/function/container/taskDetailTest.vue
src/components/projects/workflow/productCustomTaskDetail/jobBuildDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobImageDistributeDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobPluginDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue
src/components/projects/workflow/productTaskDetail/artifactDeploy.vue
src/components/projects/workflow/productTaskDetail/build.vue
src/components/projects/workflow/productTaskDetail/test.vue
src/mobile/project/workflow/product/common/taskDetailBuild.vue
src/mobile/project/workflow/product/common/taskDetailTest.vue

fix:support carriage-return in log.

fix:support carriage-return in log.

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/lang/en.js
src/lang/zh-CN.js

feat: add debug tooltip

---

src/components/common/customWorkflowBuildRows.vue
src/components/common/customWorkflowCommonRows.vue
src/components/common/workflowBuildRows.vue
src/components/projects/common/hosting/runWorkflow.vue
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/guide/helm/delivery.vue
src/components/projects/guide/k8s/delivery.vue
src/components/projects/guide/pm/delivery.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/productCustomDetail.vue
src/components/projects/workflow/productDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix: repo name width

---

src/components/projects/scanner/create.vue

feat: code scanning supports multiple repositories

feat: code scanning supports multiple repositories

---

src/components/entry/home/topbar.vue

fix:fix project alias missing when refreshed.
How it Works:

fix:fix project alias missing when refreshed.

---

src/utilities/utilities.js

fix: approval status color

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue

fix: webhook dialog

---

src/components/projects/policy/home.vue
src/components/projects/policy/policy.vue
src/components/projects/rbac/addRole.vue
src/components/setting/users/components/roleOperate.vue

feat: optimize the style of permission

feat: optimize the style of permission

---

src/components/projects/rbac/addRole.vue

show all permission items in one row

fix: show all permission items in one row

---

src/components/projects/env/k8sPmEnv/k8sServiceList.vue

fix: default image selection error

fix: default image selection error

---

src/components/projects/serviceMgr/helm/code.vue

fix: helm service style error

---

src/components/projects/serviceMgr/serviceK8s.vue

fix: update env params error

---

package.json
src/components/projects/workflow/common/statusBarChart.vue
src/components/projects/workflow/list/workflowRow.vue
yarn.lock

feat:show recent task charts in the workflow list.

feat:show recent task charts in the workflow list.

---

src/api/index.js
src/components/setting/integration/components/addJenkins.vue

feat:optimize jenkins validation behavior.

feat:optimize jenkins validation behavior.

---

src/components/setting/integration/components/sonarOperate.vue

feat:optimize sonar validation behavior.

feat:optimize sonar validation behavior.

---

src/api/index.js
src/components/setting/integration/project.vue

feat:optimize project management validation behavior.

feat:optimize project management validation behavior.

---

src/components/projects/env/env_detail/envDetailComp.vue

fix:fix permission lacking style of env change log.

fix:fix permission lacking style of env change log.

---

Dockerfile

feat:upgrade nginx version.

---

src/components/projects/common/taskList.vue
src/components/projects/workflow/productCustomDetail.vue
src/components/projects/workflow/productDetail.vue

feat: optimize workflow details list

feat: optimize workflow details list

---

src/components/projects/env/k8sPmEnv/createK8sEnv.vue
src/components/projects/guide/k8s/createEnv.vue

feat: k8s service can have no image information

feat: k8s service can have no image information

---

src/components/projects/build/envVariable.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/templateLibrary/builds/envVariable.vue
src/lang/en.js
src/lang/zh-CN.js

feat: add $<REPO>_ORG variable

feat: add $<REPO>_ORG variable

---

src/components/projects/detail_ope/components/deleteProject.vue
src/components/projects/env/env_detail/envDetailComp.vue

feat: ns and services are not deleted by default

feat: ns and services are not deleted by default

---

src/components/projects/test/common/function/container/otherSteps.vue
src/components/projects/test/common/function/functionDetail.vue

feat: test support object storage

feat: test support object storage

---

src/components/projects/env/env_detail/components/chartList.vue
src/components/projects/env/env_detail/components/serviceList.vue
src/lang/en.js
src/lang/zh-CN.js

docs: modify description

---

src/common/repoSelect.vue
src/common/serviceRepoSelect.vue
src/components/common/customWorkflowBuildRows.vue
src/components/common/customWorkflowCommonRows.vue
src/components/common/workflowBuildRows.vue
src/components/common/workflowTestRows.vue
src/components/projects/scanner/common/runScannerTask.vue
src/components/projects/scanner/create.vue
src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
src/mobile/project/workflow/product/common/workflowBuildRows.vue
src/mobile/project/workflow/product/common/workflowTestRows.vue

feat: support for hidden repos

feat: support for hidden repos

---

src/components/projects/guide/helm/runtime.vue
src/components/projects/guide/k8s/runtime.vue

feat:optimize the progress display of environment creation.

feat:optimize the progress display of environment creation.

---

src/components/projects/workflow/list/virtualListItem.vue
src/components/projects/workflow/list/workflowRow.vue

chore:chore:clean code.

---

src/components/projects/workflow/productCustomTaskDetail.vue

feat:show more data in job container.

feat:show more data in job container.

---

src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/envDetailComp.vue
src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobDeploy.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobK8sDeploy.vue
src/lang/en.js
src/lang/zh-CN.js
src/store/index.js
src/store/modules/workflowTabs.js
src/store/mutations.js

-  modify label description
-  optimize workflow list action
-  optimize environment list style
How it Works:

feat: optimize action

---

src/components/projects/build/envVariable.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/templateLibrary/builds/envVariable.vue
src/lang/en.js
src/lang/zh-CN.js

feat: add built-in test variables

feat: add built-in test variables

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

feat: custom workflow config scroll 

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
src/mobile/project/workflow/product/common/runCustomWorkflow.vue

fix:get images by image_name.

---

src/components/projects/workflow/common/runCustomWorkflow.vue

feat:using latest build config when run custome workflow.

feat:using latest build config when run custome workflow.

---

src/assets/css/component/env-detail.less
src/components/projects/env/env_detail/envDetailComp.vue

style: environment scroll behavior

style: environment scroll behavior

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

fix:using service_options in webhook trigger.

fix:using service_options in webhook trigger.

---

src/components/projects/workflow/list.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobDeploy.vue

fix: run workflow error

---

src/components/dashboard/index.vue

fix:fix dashboard breadcrumb link.

fix:fix dashboard breadcrumb link.

---

src/components/projects/workflow/common/runCustomWorkflow.vue

Reverts koderover/zadig-portal#1723

Revert "feat:using latest build config when run custome workflow."

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

Reverts koderover/zadig-portal#1725

Revert "fix:using service_options in webhook trigger."

---

src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

revert "feat:using latest build config when run custome workflow."

revert "feat:using latest build config when run custome workflow." 

---

src/components/entry/login.vue
src/components/entry/passwordLogin.vue

fix:fix login loading and validation.

fix:fix login loading and validation.

---

src/components/setting/plugins/manage.vue

feat: support other type repo

---

src/components/dashboard/status/container/customWorkflowStatus.vue
src/components/dashboard/status/container/productWorkflowStatus.vue
src/components/dashboard/status/container/scannerStatus.vue
src/components/dashboard/status/container/testStatus.vue

fix:fix style of running status page.

fix:fix style of running status page.

---

src/components/common/customWorkflowBuildRows.vue
src/components/common/workflowBuildRows.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
src/components/setting/plugins/manage.vue

fix: multi requests of infos api

---

src/router/index.js

fix:add authorization to system integration.

 fix:add authorization to system integration.

---

src/components/projects/workflow/productCustomTaskDetail.vue
src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue

fix:fix prop typo.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
src/lang/en.js
src/lang/zh-CN.js

fix: notify all members
How it Works:

fix: notify all members

---

src/api/index.js
src/components/insight/common/subTopbar.vue
src/components/insight/home.vue
src/components/insight/test/averageDuration.vue
src/components/insight/test/deploy.vue
src/components/insight/test/health.vue
src/components/insight/test/trend.vue
src/components/projects/build/zadigBuild.vue
src/router/index.js

feat:optimize the Insight experience.

feat:optimize the Insight experience. 

---

src/lang/zh-CN.js

fix(typo):fix typo of project list.

fix(typo):fix typo of project list.

---

src/assets/css/component/service-mgr.less
src/components/projects/serviceMgr/serviceK8s.vue

fix:add initial values to avoid the container being propped up.

fix:add initial values to avoid the container being propped up.

---

src/components/projects/serviceMgr/k8s/container/help.vue

Problem Summary: document link inaccurate
What's Changed: update link

fix typo: make document link more accurate

---

src/components/projects/workflow/common/runCustomWorkflow.vue

feat:add loading when get imgs.

feat:add loading when get imgs.

---

src/components/common/customWorkflowBuildRows.vue
src/components/common/customWorkflowCommonRows.vue
src/components/projects/common/integrationRegistry.vue
src/components/projects/serviceMgr/common/integrationCode.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobPlugin.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
src/components/setting/config/mail.vue
src/components/setting/config/proxy.vue
src/components/setting/helm/manage.vue
src/components/setting/integration/account.vue
src/components/setting/integration/code.vue
src/components/setting/integration/components/addJenkins.vue
src/components/setting/integration/components/sonarOperate.vue
src/components/setting/integration/other.vue
src/components/setting/integration/project.vue
src/components/setting/registry/manage.vue
src/components/setting/storage/manage.vue

feat:disable show password.
How it Works:

feat:disable show password.

---

src/components/projects/env/envDetail/envConfig/versionHistory.vue

fix:fix version

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue

fix:clean unused prop.

---

src/assets/css/component/env-detail.less
src/components/common/customWorkflowCommonRows.vue
src/components/projects/env/envDetail/envDetailComp.vue
src/components/projects/rbac/addRole.vue
src/components/projects/scanner/common/advancedConfig.vue
src/components/projects/scanner/create.vue
src/components/projects/serviceMgr/helm/components/common/chartRepo.vue
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/customWorkflowDetail.vue
src/components/projects/workflow/list/workflowRow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/components/setting/users/components/roleOperate.vue
src/lang/en.js
src/lang/zh-CN.js

feat: optimize use

---

src/components/projects/detail/components/cusDeliverable.vue
src/components/projects/serviceMgr/k8s/container/policy.vue

fix:fix image name not update.

fix:fix image name not update.

---

src/components/setting/users/manage.vue

feat:optimaze style of user management.

feat:optimaze style of user management.

---

src/assets/css/component/service-tree.less
src/components/projects/serviceMgr/common/serviceTree.vue

fix:fix style of buttons in service-tree.

fix:fix style of buttons in service-tree.

---

src/components/projects/workflow/common/repoJump.vue

feat:enable gerrit commit link.

feat:enable gerrit commit link.

---

src/api/index.js
src/components/entry/components/forgetPassword.vue
src/components/entry/components/signUp.vue
src/components/entry/login.vue
src/components/profile/info.vue
src/lang/en.js
src/lang/zh-CN.js
src/store/modules/login.js
src/utilities/utilities.js

feat:show captcha after login failed.

feat:show captcha after login failed.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/envTypeSelect.vue

feat:show background when dropdown item's active.

feat:show background when dropdown item's active.

---

src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue

fix:fix repo validation in trigger.

fix:fix repo validation in trigger.

---

src/components/common/testTrigger.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue

feat:add new tooltip.

---

src/common/serviceRepoSelect.vue

fix:fix render is blocked by errors.

fix:fix render is blocked by errors.

---

src/components/projects/workflow/customWorkflowTaskDetail/jobDeployDetail.vue

fix:fix style of job deploy.

---

src/api/index.js
src/common/xtermDebug.vue
src/components/projects/env/envDetailComp.vue
src/components/projects/env/k8s/detail/serviceList.vue
src/components/projects/env/k8s/service/serviceDetail.vue
src/components/projects/env/pm/service/pmServiceDetail.vue
src/components/projects/workflow/customWorkflowTaskDetail/jobDeployDetail.vue
src/mobile/project/env/helmServiceDetail.vue
src/mobile/project/env/k8sServiceDetail.vue
src/mobile/project/env/pmServiceDetail.vue

feat:zadig-deploy support linking to the environment in task detail.

feat:zadig-deploy support linking to the environment in task detail.

---

src/api/index.js
src/components/projects/workflow/common/runCustomWorkflow.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue

fix:using job's registry_id instead of global prop.

fix:using job's registry_id instead of global prop.

---

src/common/repoSelect.vue

feat:interrupt initialization request when searching for namespace.

feat:interrupt initialization request when searching for namespace.

---

src/components/projects/env/k8s/creation/createK8sEnv.vue

fix:get current cluster's namesapces when soure env changed.

fix:get current cluster's namesapces when soure env changed.

---

src/components/templateLibrary/dockerfile/fileTree.vue
src/components/templateLibrary/dockerfile/index.vue
src/components/templateLibrary/k8s/fileTree.vue

fix:fix behavior after saving templates.

fix:fix behavior after saving templates.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobK8sDeploy.vue

fix:clean workload type and using response's data as image_name in custom job.

fix:clean workload type and using response's data as image_name in custom job.

---

src/components/projects/serviceMgr/helm/components/helm/aside.vue
src/components/projects/serviceMgr/serviceHost.vue
src/components/projects/serviceMgr/servicePm.vue

fix:fix component path.

---

src/components/projects/workflow/workflowEditor/customWorkflow/components/base/settings.vue
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue

fix:change prop.

---

src/components/projects/serviceMgr/k8s/serviceAside.vue

fix:fix deletion index.

---

src/components/projects/workflow/productWorkflowDetail.vue
src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
src/components/projects/workflow/workflowEditor/customWorkflow/config.js
src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
src/lang/en.js
src/lang/zh-CN.js

fix:fix minor bugs in workflow.

fix:fix minor bugs in workflow. 

---

src/components/templateLibrary/k8s/fileAside.vue

fix:fix permission binding.

---

src/components/projects/detail/detail.vue

fix:check permission.

---

src/api/index.js
src/components/entry/home/topbar.vue
src/mobile/profile.vue

fix:fix logout.

---

src/components/projects/workflow/customWorkflowTaskDetail.vue

fix:fix deployType missing.

---

src/components/projects/env/helm/common/updateHelmEnvChart.vue

fix:fix onboarding env creation.

fix:fix onboarding env creation.

---

src/components/entry/home/subTopbar.vue
src/lang/en.js
src/lang/zh-CN.js

feat:add production services tooltip.

feat:add production services tooltip.

---

.stylelintrc.json

fix:fix stylelint rule.

---

src/assets/css/component/service-editor.less

fix:fix style of editor.

---

src/components/entry/home/subTopbar.vue

fix:fix stylelint.

---

src/components/projects/env/k8s/creation/k8sServiceList.vue
src/components/projects/env/k8s/detail/manageK8sServicesDialog.vue

[feat:add tooltip.](https://github.com/koderover/zadig-portal/commit/ce5af41fcee9777fa3bd61381b30dbfd260ae8a8)

feat:add tooltip.

---

src/lang/en.js
src/lang/zh-CN.js

fix:fix i18n missing.

---

src/components/entry/home/subTopbar.vue

fix:fix pm services missing in subtopbar.

fix:fix pm services missing in subtopbar.

---

src/components/entry/home/subTopbar.vue
src/components/projects/serviceMgr/common/importFromTemplate.vue
src/components/projects/serviceMgr/helm/components/common/templateRepo.vue

fix:add service name validation rules.

fix:add service name validation rules.

---

src/App.vue
src/api/index.js
src/components/entry/installation.vue
src/lang/en.js
src/lang/zh-CN.js
src/router/index.js

feat:add installation page.

---

src/components/entry/home/subTopbar.vue

fix:fix dom node not found when checking permission.

fix:fix dom node not found when checking permission.
